# Host-specific NixOS config for g14 (ASUS Zephyrus laptop).
#
# flake.nixosConfigurations.g14 is generated by modules/builder.nix from
# lib/registry.nix. This module is referenced from the g14 entry's
# extraModules (because nixos-hardware imports can't safely live in
# alwaysImport -- imports must stay unconditional).
#
# Long-form pattern: `imports` is unconditional; `config` is gated as
# defense-in-depth even though only ever loaded on g14.
{ self, ... }:
{
  flake.nixosModules.g14 =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    let
      # The GA401's fingerprint reader is a Goodix 27c6:521d. Mainline libfprint
      # does NOT support it -- the pid only appears in libfprint's autosuspend
      # hwdb whitelist (a power-management list, not a driver list), so fprintd
      # alone finds no device. Goodix ships no Linux driver and won't.
      #
      # The only working driver is the reverse-engineered `goodixtls` set from
      # infinytum's libfprint fork (the same code the AUR `libfprint-goodix-521d`
      # package uses). That fork is abandoned at libfprint 1.94.1 (Nov 2021), and
      # the AUR route is to run the whole stale 1.94.1 library -- which nixpkgs'
      # fprintd (>= 1.94.9 required) will not build against.
      #
      # Instead we graft just the driver onto nixpkgs' current libfprint: the
      # fork's addition is entirely self-contained (a new drivers/goodixtls/
      # directory plus meson wiring), so it ports cleanly and we keep an
      # up-to-date libfprint. Upstream's own test suite still passes.
      goodixtlsSrc = pkgs.fetchFromGitHub {
        owner = "infinytum";
        repo = "libfprint";
        rev = "5e14af7f136265383ca27756455f00954eef5db1"; # branch `unstable`
        hash = "sha256-MFhPsTF0oLUMJ9BIRZnSHj9VRwtHJxvWv0WT5zz7vDY=";
      };

      libfprint-goodixtls = pkgs.libfprint.overrideAttrs (old: {
        pname = "libfprint-goodixtls";

        postPatch = (old.postPatch or "") + ''
          cp -r ${goodixtlsSrc}/libfprint/drivers/goodixtls libfprint/drivers/
          chmod -R u+w libfprint/drivers/goodixtls

          # The fork treats this press sensor as a swipe sensor. See the patch
          # header; without it the sensor enrols but never matches.
          patch -p1 < ${./goodixtls-52xd-press-capture.patch}

          substituteInPlace meson.build \
            --replace-fail "    'goodixmoc',
    'nb1010'," "    'goodixmoc',
    'goodixtls511',
    'goodixtls52xd',
    'goodixtls53xd',
    'nb1010'," \
            --replace-fail "    'uru4000' : [ 'openssl' ]," "    'uru4000' : [ 'openssl' ],
    'goodixtls511' : [ 'openssl', 'goodixtls' ],
    'goodixtls52xd' : [ 'openssl', 'goodixtls' ],
    'goodixtls53xd' : [ 'openssl', 'goodixtls' ],"

          substituteInPlace libfprint/meson.build \
            --replace-fail "    'focaltech_moc' :
        [ 'drivers/focaltech_moc/focaltech_moc.c' ],
}" "    'focaltech_moc' :
        [ 'drivers/focaltech_moc/focaltech_moc.c' ],
    'goodixtls511' :
        [ 'drivers/goodixtls/goodix511.c' ],
    'goodixtls52xd' :
        [ 'drivers/goodixtls/goodix52xd.c' ],
    'goodixtls53xd' :
        [ 'drivers/goodixtls/goodix53xd.c' ],
}" \
            --replace-fail "    'openssl' :
        [ ]," "    'openssl' :
        [ ],
    'goodixtls' :
        [ 'drivers/goodixtls/goodix_proto.c', 'drivers/goodixtls/goodix.c', 'drivers/goodixtls/goodixtls.c' ],"

          # These three pids are now claimed by real drivers, so they must leave
          # the "no driver, just autosuspend" whitelist and gain driver sections
          # in the shipped hwdb. libfprint's own `udev-hwdb` test diffs the
          # checked-in file against the generated one, so it verifies this edit.
          substituteInPlace libfprint/fprint-list-udev-hwdb.c \
            --replace-fail "  { .vid = 0x27c6, .pid = 0x5110 },
" "" \
            --replace-fail "  { .vid = 0x27c6, .pid = 0x521d },
" "" \
            --replace-fail "  { .vid = 0x27c6, .pid = 0x538d },
" ""

          substituteInPlace data/autosuspend.hwdb \
            --replace-fail "usb:v27C6p5110*
" "" \
            --replace-fail "usb:v27C6p521D*
" "" \
            --replace-fail "usb:v27C6p538D*
" "" \
            --replace-fail "# Supported by libfprint driver nb1010" "# Supported by libfprint driver goodixtls511
usb:v27C6p5110*
 ID_AUTOSUSPEND=1
 ID_PERSIST=0

# Supported by libfprint driver goodixtls52xd
usb:v27C6p521D*
 ID_AUTOSUSPEND=1
 ID_PERSIST=0

# Supported by libfprint driver goodixtls53xd
usb:v27C6p538D*
 ID_AUTOSUSPEND=1
 ID_PERSIST=0

# Supported by libfprint driver nb1010"
        '';

        # The driver passes `&payload` (guint8 (*)[N]) where a guint8* is wanted.
        # Same address, but GCC 14 makes this an error by default.
        env = (old.env or { }) // {
          NIX_CFLAGS_COMPILE = "-Wno-incompatible-pointer-types";
        };
      });
    in
    {
      imports = [
        "${builtins.fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }}/asus/zephyrus/ga401"
      ];
      config = lib.mkIf (config.noughty.host.name == "g14") {
        # Shared desktop baseline (DE selection, steam, bluetooth, wheel,
        # networkmanager, nameservers, bolt, libinput quirks) now lives in
        # modules/desktop.nix, gated on noughty.host.is.nixosDesktop.
        #
        # The old sing-box proxy.ipRanges block is gone: g14 now reaches the
        # homelab over the headscale tailnet (modules/tailnet.nix), not a
        # local SOCKS proxy. The HM `proxy` module is Mac-only now.
        networking.hostName = "g14";

        # The `deploy` CLI used to be listed here, per-host. It is now part of
        # the shared NixOS-desktop baseline in modules/desktop.nix, so blac gets
        # it on the same terms rather than g14 being the one laptop that can
        # deploy. The build-offload half still lives in lib/registry.nix as the
        # `builder-client` import (see the comment there).

        boot.loader.systemd-boot.enable = false;
        boot.loader.limine = {
          enable = true;
        };
        boot.loader.efi.canTouchEfiVariables = true;

        systemd.tmpfiles.rules = [
          "w /sys/devices/system/cpu/cpufreq/boost - - - - 0"
        ];
        hardware.nvidia.prime = {
          offload.enable = lib.mkForce false;
          reverseSync.enable = true;
          allowExternalGpu = true;
        };
        programs.rog-control-center.enable = true;
        boot.extraModprobeConfig = ''
          options nvidia NVreg_EnableGpuFirmware=0
        '';
        hardware.nvidia = {
          open = false;
          powerManagement.enable = false;
          modesetting.enable = true;
        };
        systemd.services.nvidia-powerd = {
          unitConfig.StartLimitAction = "none";
          serviceConfig.Restart = "no";
          wantedBy = lib.mkForce [ ];
        };
        services.upower.enable = true;

        # EasyEffects preset. The daemon is enabled for every NixOS desktop
        # (services.easyeffects in modules/desktop.nix), but this preset is
        # tuned for the GA401's own speakers, so it is host-scoped and lives
        # next to this module rather than in the shared desktop one.
        #
        # HM writes extraPresets into $XDG_DATA_HOME/easyeffects/<folder>/,
        # picking the folder from the JSON's top-level key -- ours is "output",
        # so this lands as ~/.local/share/easyeffects/output/g14.json. `preset`
        # is what actually applies it: it becomes `--load-preset g14` on the
        # daemon's ExecStart, so it is in effect on a fresh home directory too.
        #
        # The file is a store symlink, so the EasyEffects GUI cannot save over
        # it. To change the tuning: tweak it in the GUI, save it under another
        # name, and copy that JSON over ./g14.json.
        home-manager.users.phonkd.services.easyeffects = {
          extraPresets.g14 = builtins.fromJSON (builtins.readFile ./g14.json);
          preset = "g14";
        };

        # AirPlay audio *out*. g14 is the sender here: reachable AirPlay
        # receivers become ordinary PipeWire sinks, so anything (browser,
        # mpv, Spotify) can pick one as its output device. Receiving is the
        # other stack entirely -- that is shairport-sync on 203-media, see
        # modules/gigaplayer.nix.
        #
        # PipeWire already ships libpipewire-module-raop-{discover,sink} and
        # the sender itself is fine: with the sink pointed straight at
        # 203-media's shairport-sync (the snapserver AirPlay input, :5000) the
        # RTSP handshake completes -- OPTIONS/ANNOUNCE/SETUP/RECORD all 200 --
        # and snapserver's "Airplay" stream flips idle -> playing for as long
        # as audio flows. Three things were missing around it:
        #
        # 1. avahi. module-raop-discover browses mDNS through avahi's client
        #    library; with no daemon it finds nothing and no sink ever shows
        #    up. Publishing stays off -- the laptop only browses, it does not
        #    announce itself.
        # 2. module-raop-discover is not in PipeWire's default module set, so
        #    nothing loads it. Hence the drop-in below.
        # 3. The firewall, which is what actually broke playback on the LAN.
        #    RAOP hands the receiver a control and a timing port and the
        #    receiver connects *back* to them; NixOS' default-deny input chain
        #    drops that. The failure is silent and misleading: a Sonos answers
        #    OPTIONS, POST /auth-setup and ANNOUNCE with 200 and then simply
        #    never replies to SETUP, so the session hangs mid-handshake with
        #    no error logged anywhere. Measured on this host beforehand: 25 s
        #    of passive listening on wlp2s0 caught zero mDNS and zero SSDP
        #    packets, on a LAN with three Sonos and an Apple TV on it.
        #
        # Scope: this drives AirPlay 1 (RAOP) receivers. It cannot drive
        # anything that insists on HomeKit pairing -- PipeWire implements
        # /auth-setup but not pair-setup/pair-verify, which is why the Apple
        # TV on this LAN answers 403 Forbidden to the very first OPTIONS.
        # Sonos speakers do speak the legacy path (they 200 the auth-setup and
        # 403 an unencrypted ANNOUNCE, i.e. they want it), so they are the
        # expected beneficiaries once the return path is open.
        services.avahi = {
          enable = true;
          nssmdns4 = true;
          openFirewall = true; # UDP 5353 in, or the discovery replies are dropped
        };
        services.pipewire.raopOpenFirewall = true; # UDP 6001-6002: RAOP control + timing
        services.pipewire.extraConfig.pipewire."10-airplay" = {
          "context.modules" = [ { name = "libpipewire-module-raop-discover"; } ];
        };

        # Fingerprint reader (Goodix 27c6:521d): driven, provisioned, enrols --
        # and left DISABLED, because it cannot authenticate. See
        # plans/g14-fingerprint.md for the full write-up.
        #
        # The short version: the driver works. Captures are clean 64x80 images
        # with well-defined ridges, and NBIS binarizes them correctly. But the
        # sensor window is only ~2.3 x 2.8 mm (measured from the ridge period in
        # those captures), and a window that small physically contains 1-2
        # minutiae. NBIS finds exactly that -- 0 to 2 per capture. bozorth3's
        # threshold of 24 needs an order of magnitude more, so verification
        # scores 0. No driver change can create minutiae that are not inside the
        # window; this is the sensor's size, not a bug. It is also why upstream
        # libfprint declined to support it. Windows works only via Goodix's
        # proprietary non-minutiae matcher, which is not available here.
        #
        # Do NOT "fix" this by lowering bz3_threshold. `fprintAuth` defaults to
        # services.fprintd.enable, so this sits in front of sudo and sddm, and a
        # threshold low enough to admit these scores authenticates on noise.
        #
        # Everything above (the libfprint graft, the driver patch,
        # scripts/goodix-521d-provision.sh) is correct and stays: the sensor is
        # already provisioned, so if a non-minutiae matcher ever lands this is
        # one boolean. Leaving it enabled-but-broken would make every sudo and
        # every login wait on a finger that can never match.
        services.fprintd = {
          enable = false;
          package = pkgs.fprintd.override { libfprint = libfprint-goodixtls; };
        };
      };
    };
}
