# Host-specific NixOS config for 201-mono (homelab server VM).
#
# flake.nixosConfigurations."201-mono" is generated by modules/builder.nix
# from lib/registry.nix. The cross-host feature modules (traefik,
# dashboard, *arrs, etc.) live in alwaysImport and self-gate on tags:
#   reverse-proxy  -> traefik/dashboard/ddns/authelia/orphans
#   homelab-server -> syncthing/vaultwarden/paperless/arr/garage
#   is.server      -> server-globalconfig/server-sops
#
# This file owns the bits that are truly unique to the 201-mono box:
# hostname, network interface, wireguard. (Samba shares were moved to
# 203-media -- see modules/hosts/203-media.nix.) Both nixosModules below
# self-gate defensively on host.name even though they're only referenced
# from the "201-mono" registry entry's extraModules -- belt-and-braces in
# case of accidental import elsewhere.
{ ... }:
{
  flake.nixosModules."201-mono" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "201-mono") {
      label.labels = [ "vm" ];
      networking.interfaces.ens18.ipv4.addresses = [
        {
          address = "192.168.3.201";
          prefixLength = 24;
        }
      ];
      # Accept router advertisements even though this host forwards.
      #
      # 2, not 1, and the difference is the whole point. The kernel reads
      # accept_ra = 1 as "accept RAs *if forwarding is disabled*", and 201
      # forwards: services.tailscale's useRoutingFeatures = "server" turns on
      # net.ipv6.conf.all.forwarding so it can act as the tailnet exit node
      # (modules/tailnet.nix). With forwarding on, accept_ra = 1 is silently
      # equivalent to 0 -- RAs arrive and are dropped, no SLAAC address, no v6
      # default route, and nothing in the logs to say so. Only 2 overrules it.
      #
      # This is what makes the exit node's IPv6 half real. An exit node always
      # advertises ::/0 alongside 0.0.0.0/0 -- neither tailscale nor headscale
      # will let the pair be split, see the note in
      # modules/homelab/apps/headscale-policy.hujson -- so before 201 had a v6
      # uplink of its own, every client selecting it inherited a v6 default
      # aimed at a host that could not forward v6.
      #
      # Init7 delegates a static /48 by DHCPv6-PD; the UniFi gateway hands this
      # LAN a /64 out of it and 201 autoconfigures from the RA. Nothing here
      # pins an address, so a prefix change needs no config change.
      boot.kernel.sysctl."net.ipv6.conf.ens18.accept_ra" = 2;

      security.sudo.wheelNeedsPassword = false;
      networking.hostName = "201-mono";
      networking.networkmanager.dhcp = "internal";
      networking.firewall.allowedTCPPorts = [
        80
        443
        22
      ];
      boot.loader.systemd-boot.configurationLimit = 10;
      # (Distributed-build client wiring comes from builder-client, imported
      # via oldblac-vm -- see modules/hosts/types/server/builder.nix.)
    };
  flake.nixosModules."201-wireguard" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "201-mono") {
      networking.wireguard.interfaces = {
        wg0 = {
          # Server private key (generate with: wg genkey)
          # # 1. Move into the directory
          # cd /etc/wireguard/

          # # 2. Set umask to 077 (makes files readable only by the owner)
          # # and generate the key in one go
          # (umask 077; wg genkey > private.key)

          # # 3. Generate the public key from that private key
          # wg pubkey < private.key > public.key
          #
          # create client keys the same way
          # (umask 077; wg genkey > client_private.key)
          # wg pubkey < client_private.key > client_public.key
          privateKeyFile = "/etc/wireguard/private.key";
          listenPort = 51820;

          ips = [ "10.8.0.1/24" ];

          peers = [
            {
              publicKey = "CCr+3q0HCQKSBX2GV0l4OeflCYGdlbOqQ17rn0Khv3I=";
              allowedIPs = [ "10.8.0.2/32" ];
            }
            {
              publicKey = "8Cu7eXjrMef0k1CN0amimPLI2YKP/nKyFgHAH0sDMyg=";
              allowedIPs = [ "10.8.0.3/32" ];
            }
          ];
        };
      };

      networking.firewall = {
        allowedUDPPorts = [ 51820 ];
      };

      networking.nat = {
        enable = true;
        externalInterface = "ens18";
        internalInterfaces = [ "wg0" ];
      };
    };
}
