# Host-specific NixOS config for 201-mono (homelab server VM).
#
# flake.nixosConfigurations."201-mono" is generated by modules/builder.nix
# from lib/registry.nix. The cross-host feature modules (traefik,
# dashboard, *arrs, etc.) live in alwaysImport and self-gate on tags:
#   reverse-proxy  -> traefik/dashboard/ddns/authelia/orphans/teleport
#   homelab-server -> syncthing/vaultwarden/paperless/arr/aislop/garage
#   is.server      -> server-globalconfig/server-sops
#
# This file owns the bits that are truly unique to the 201-mono box:
# hostname, network interface, samba shares, wireguard. All three
# nixosModules below self-gate defensively on host.name even though
# they're only referenced from the "201-mono" registry entry's
# extraModules -- belt-and-braces in case of accidental import elsewhere.
{ ... }:
{
  flake.nixosModules."201-mono" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "201-mono") {
      label.labels = [ "vm" ];
      networking.interfaces.ens18.ipv4.addresses = [
        {
          address = "192.168.1.201";
          prefixLength = 24;
        }
      ];
      security.sudo.wheelNeedsPassword = false;
      networking.hostName = "201-mono";
      networking.networkmanager.dhcp = "internal";
      networking.firewall.allowedTCPPorts = [
        80
        443
        22
      ];
    };
  flake.nixosModules."201-wireguard" =
    { config, pkgs, lib, ... }:
    lib.mkIf (config.noughty.host.name == "201-mono") {
      networking.wireguard.interfaces = {
        wg0 = {
          # Server private key (generate with: wg genkey)
          # # 1. Move into the directory
          # cd /etc/wireguard/

          # # 2. Set umask to 077 (makes files readable only by the owner)
          # # and generate the key in one go
          # (umask 077; wg genkey > private.key)

          # # 3. Generate the public key from that private key
          # wg pubkey < private.key > public.key
          #
          # create client keys the same way
          # (umask 077; wg genkey > client_private.key)
          # wg pubkey < client_private.key > client_public.key
          privateKeyFile = "/etc/wireguard/private.key";
          listenPort = 51820;

          ips = [ "10.8.0.1/24" ];

          peers = [
            {
              publicKey = "CCr+3q0HCQKSBX2GV0l4OeflCYGdlbOqQ17rn0Khv3I=";
              allowedIPs = [ "10.8.0.2/32" ];
            }
            {
              publicKey = "8Cu7eXjrMef0k1CN0amimPLI2YKP/nKyFgHAH0sDMyg=";
              allowedIPs = [ "10.8.0.3/32" ];
            }
          ];
        };
      };

      networking.firewall = {
        allowedUDPPorts = [ 51820 ];
      };

      networking.nat = {
        enable = true;
        externalInterface = "ens18";
        internalInterfaces = [ "wg0" ];
      };
    };
  flake.nixosModules."201-shares" =
    { config, pkgs, lib, ... }:
    lib.mkIf (config.noughty.host.name == "201-mono") {
      systemd.tmpfiles.rules = [
        "d /mnt/Shares 0755 root root -"
        "d /mnt/Shares/Public 2775 smbpublic smbpublic -"
        "d /mnt/Shares/SemiPublic 2770 phonkd phonkd -"
        "d /mnt/Shares/this-is-my-own-private-property-and-you-are-not-welcome-here 0750 phonkd phonkd -"
      ];

      users.users.smbpublic = {
        isSystemUser = true;
        description = "Samba guest share user";
        group = "smbpublic";
        home = "/var/empty";
      };

      users.groups.smbpublic = { };
      services.samba = {
        enable = true;
        securityType = "user";
        openFirewall = true;
        settings = {
          global = {
            "workgroup" = "WORKGROUP";
            "server string" = "baaaalright";
            "netbios name" = "smbnix";
            "security" = "user";
            "hosts allow" = "192.168.1.0/24 10.89.0.0/24 127.0.0.1 localhost 10.8.0.1/24";
            "hosts deny" = "0.0.0.0/0";
            "guest account" = "smbpublic";
            "map to guest" = "bad user";
            "host msdfs" = "no";
          };
          "public" = {
            "path" = "/mnt/Shares/Public";
            "browseable" = "yes";
            "read only" = "no";
            "guest ok" = "yes";
            "create mask" = "0664";
            "directory mask" = "2775";
            "force user" = "smbpublic";
            "force group" = "smbpublic";
          };
          "semipublic" = {
            "path" = "/mnt/Shares/SemiPublic";
            "browseable" = "yes";
            "read only" = "yes";
            "guest ok" = "yes";
            "create mask" = "0664";
            "directory mask" = "2775";
            "write list" = "@phonkd phonkd";
            "force create mode" = "0660";
            "force directory mode" = "2770";
            "guest account" = "smbpublic";
          };
          "private" = {
            "path" = "/mnt/Shares/this-is-my-own-private-property-and-you-are-not-welcome-here";
            "browseable" = "yes";
            "read only" = "no";
            "guest ok" = "no";
            "create mask" = "0644";
            "directory mask" = "0755";
            "force user" = "phonkd";
            "force group" = "phonkd";
          };
        };
      };

      services.samba-wsdd = {
        enable = true;
        openFirewall = true;
      };

      networking.firewall.enable = true;
      networking.firewall.allowPing = true;
      services.avahi = {
        enable = true;
        nssmdns = true;
        publish = {
          enable = true;
          addresses = true;
          domain = true;
          hinfo = true;
          userServices = true;
          workstation = true;
        };
      };
      fileSystems."/mnt/Shares" = {
        device = "/dev/disk/by-id/virtio-vm-202-disk-1";
        fsType = "ext4";
        autoFormat = true;
        autoResize = true;
        options = [
          "users"
          "nofail"
        ];
      };
    };
}
