# Host-specific NixOS config for 201-mono (homelab server VM), generated by
# modules/builder.nix from lib/registry.nix. Cross-host feature modules
# (traefik, dashboard, *arrs, etc.) live in alwaysImport and self-gate on
# tags: reverse-proxy -> traefik/dashboard/ddns/authelia/orphans,
# homelab-server -> syncthing/vaultwarden/paperless/arr/garage,
# is.server -> server-globalconfig/server-sops.
#
# This file owns only what's unique to 201-mono: hostname, network
# interface, wireguard (Samba shares moved to 203-media). Both modules below
# self-gate on host.name too, belt-and-braces against accidental import
# elsewhere.
{ ... }:
{
  flake.nixosModules."201-mono" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "201-mono") {
      label.labels = [ "vm" ];
      networking.interfaces.ens18.ipv4.addresses = [
        {
          address = "192.168.3.201";
          prefixLength = 24;
        }
      ];
      # accept_ra = 2, not 1: the kernel treats accept_ra=1 as "accept RAs
      # *only if forwarding is disabled*", and 201 forwards
      # (services.tailscale's useRoutingFeatures = "server" turns on
      # net.ipv6.conf.all.forwarding so it can be the tailnet exit node,
      # modules/tailnet.nix). With forwarding on, accept_ra=1 silently
      # behaves like 0 -- RAs are dropped, no SLAAC address, no v6 default
      # route, nothing logged. Only 2 overrules it.
      #
      # This is what makes the exit node's v6 half real: an exit node always
      # advertises ::/0 alongside 0.0.0.0/0 (tailscale/headscale won't split
      # the pair -- see modules/homelab/apps/headscale-policy.hujson), so
      # without a v6 uplink here every client picking this exit node got a
      # v6 default route to a host that couldn't forward v6.
      #
      # Init7 delegates a static /48 via DHCPv6-PD; the UniFi gateway hands
      # this LAN a /64 and 201 autoconfigures from the RA -- no address
      # pinned here, so a prefix change needs no config change.
      boot.kernel.sysctl."net.ipv6.conf.ens18.accept_ra" = 2;

      security.sudo.wheelNeedsPassword = false;
      networking.hostName = "201-mono";
      networking.networkmanager.dhcp = "internal";
      networking.firewall.allowedTCPPorts = [
        80
        443
        22
      ];
      boot.loader.systemd-boot.configurationLimit = 10;
      # Distributed-build client wiring comes from builder-client, imported
      # via oldblac-vm -- see modules/hosts/types/server/builder.nix.
    };
  flake.nixosModules."201-wireguard" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "201-mono") {
      networking.wireguard.interfaces = {
        wg0 = {
          # Generate with: (umask 077; wg genkey > private.key); wg pubkey <
          # private.key > public.key. Client keys the same way.
          privateKeyFile = "/etc/wireguard/private.key";
          listenPort = 51820;

          ips = [ "10.8.0.1/24" ];

          peers = [
            {
              publicKey = "CCr+3q0HCQKSBX2GV0l4OeflCYGdlbOqQ17rn0Khv3I=";
              allowedIPs = [ "10.8.0.2/32" ];
            }
            {
              publicKey = "8Cu7eXjrMef0k1CN0amimPLI2YKP/nKyFgHAH0sDMyg=";
              allowedIPs = [ "10.8.0.3/32" ];
            }
          ];
        };
      };

      networking.firewall = {
        allowedUDPPorts = [ 51820 ];
      };

      networking.nat = {
        enable = true;
        externalInterface = "ens18";
        internalInterfaces = [ "wg0" ];
      };
    };
}
