# Host-specific NixOS config for 203-media (gigaplayer-server VM).
#
# flake.nixosConfigurations."203-media" is generated by modules/builder.nix
# from lib/registry.nix. Cross-host modules (gigaplayer-server, server
# baseline) live in alwaysImport and self-gate on tags / is.server.
{ ... }:
{
  flake.nixosModules."203-media" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "203-media") {
      label.labels = [ "vm" ];
      networking.useDHCP = lib.mkDefault false;
      networking.interfaces = {
        ens18.ipv4.addresses = [
          # {
          #   address = "192.168.3.203";
          #   prefixLength = 24;
          # }
          {
            address = "192.168.1.203";
            prefixLength = 24;
          }
        ];
        ens19.ipv4.addresses = [
          {
            address = "192.168.3.203";
            prefixLength = 24;
          }
        ];
      };

      # Default route via ens18; a second table makes replies to traffic
      # arriving on ens19 go back out ens19 (so both addresses stay reachable
      # from remote subnets, not just their own /24).
      networking.defaultGateway = {
        address = "192.168.1.1";
        interface = "ens18";
      };
      networking.iproute2.enable = true;
      networking.localCommands = ''
        ip route flush table 203 2>/dev/null || true
        ip route add default via 192.168.3.1 dev ens19 table 203
        ip rule del from 192.168.3.203 lookup 203 2>/dev/null || true
        ip rule add from 192.168.3.203 lookup 203
      '';

      networking.firewall.allowedTCPPorts = [
        22
      ];
      swapDevices = [
        {
          device = "/var/lib/swapfile";
          size = 4 * 1024;
        }
      ];
      nix.gc = lib.mkForce {
        automatic = true;
        dates = "daily";
        options = "--delete-older-than 3d";
      };
      nix.settings.require-sigs = false;

      fileSystems."/mnt/Shares" = {
        device = "/dev/vdb";
        fsType = "ext4";
        autoFormat = true;
        autoResize = true;
        options = [
          "users"
          "nofail"
        ];
      };
    };
}
