# Host-specific NixOS config for 203-media (gigaplayer-server VM).
#
# flake.nixosConfigurations."203-media" is generated by modules/builder.nix
# from lib/registry.nix. Cross-host modules (gigaplayer-server, server
# baseline) live in alwaysImport and self-gate on tags / is.server.
#
# The 203-shares module below holds the Samba file-sharing stack that was
# previously on 201-mono (moved together with its data disk in Proxmox).
{ ... }:
{
  flake.nixosModules."203-media" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "203-media") {
      label.labels = [ "vm" ];
      # Passwordless sudo so `deploy 203-media` (deploy-rs) can activate the
      # system profile as root over ssh non-interactively — matches 201/204/205
      # and the Hetzner VMs.
      security.sudo.wheelNeedsPassword = false;
      networking.hostName = "203-media";
      networking.useDHCP = lib.mkForce false;
      networking.interfaces = {
        ens18.ipv4.addresses = [
          # {
          #   address = "192.168.3.203";
          #   prefixLength = 24;
          # }
          {
            address = "192.168.1.203";
            prefixLength = 24;
          }
        ];
        ens19.ipv4.addresses = [
          {
            address = "192.168.3.203";
            prefixLength = 24;
          }
        ];
      };

      # Default route via ens18; a second table makes replies to traffic
      # arriving on ens19 go back out ens19 (so both addresses stay reachable
      # from remote subnets, not just their own /24).
      networking.defaultGateway = {
        address = lib.mkForce "192.168.1.1";
        interface = "ens18";
      };

      # Static networking (useDHCP = false) means DHCP never supplies a
      # resolver, so without this resolvconf writes an empty /etc/resolv.conf
      # and the host can't resolve anything external. That broke
      # `deploy 203` specifically: deploy-rs pushes with
      # `nix copy --substitute-on-destination`, which makes THIS host pull
      # closures from cache.nixos.org — impossible with no nameserver, so the
      # deploy fell back to source-building (e.g. ollama-cuda, ~3h) or the
      # daemon's substituter workers crashed under the flood of failed
      # lookups. homelab-dns runs on 201; the router is the fallback.
      networking.nameservers = [
        "192.168.3.201"
        "192.168.3.1"
      ];
      networking.iproute2.enable = true;
      # `onlink` is required: this service can run before ens19 has its
      # 192.168.3.203/24 address, and without it `ip route add ... via
      # 192.168.3.1` fails with "Nexthop has invalid gateway" (the gateway
      # isn't yet on-link), which aborts the whole script before the ip rule
      # is installed. onlink forces the kernel to treat the gateway as
      # directly reachable on ens19 regardless of address-assignment timing.
      networking.localCommands = ''
        ip route flush table 203 2>/dev/null || true
        ip route add default via 192.168.3.1 dev ens19 table 203 onlink
        ip rule del from 192.168.3.203 lookup 203 2>/dev/null || true
        ip rule add from 192.168.3.203 lookup 203
      '';

      networking.firewall.allowedTCPPorts = [
        22
        11434 # ollama — 204-agent (slop-trove) reaches this over ens19/192.168.3.0
      ];

      # Embeddings for slop-trove (bge-m3) on the RTX 3060 Ti passed through
      # for Jellyfin transcoding (see arr-slime.nix) — idle GPU cycles, and
      # unlike blac this host is always on. Same 192.168.3.0/24 as 204-agent
      # (via ens19), so no inter-VLAN routing needed.
      services.ollama = {
        enable = true;
        package = pkgs.ollama-cuda;
        host = "0.0.0.0";
        port = 11434;
        loadModels = [ "bge-m3" ];
      };
      swapDevices = [
        {
          device = "/var/lib/swapfile";
          size = 4 * 1024;
        }
      ];
      nix.gc = lib.mkForce {
        automatic = true;
        dates = "daily";
        options = "--delete-older-than 3d";
      };
      nix.settings.require-sigs = false;
    };

  # Samba file shares, moved from 201-mono together with the data disk.
  # The disk was reassigned to the 203 VM in Proxmox with the serial
  # "shares", so it appears at /dev/disk/by-id/virtio-shares.
  flake.nixosModules."203-shares" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "203-media") {
      systemd.tmpfiles.rules = [
        "d /mnt/Shares 0755 root root -"
        "d /mnt/solo-sata 0755 root root -"
        "d /mnt/Shares/Public 2775 smbpublic smbpublic -"
        "d /mnt/Shares/SemiPublic 2770 phonkd phonkd -"
        "d /mnt/Shares/this-is-my-own-private-property-and-you-are-not-welcome-here 0750 phonkd phonkd -"
        "d /mnt/Shares/this-is-my-own-private-property-and-you-are-not-welcome-here/clips 0750 phonkd phonkd -"
        # The private share's ACL is group::--- so being in the `phonkd` group
        # doesn't help. Jellyfin only needs the clips library, so give it bare
        # traverse (x, no r) on the private root -- it can cd into a path it
        # already knows but can't list the root's contents -- and full
        # read+execute only on clips itself. A+ recurses over existing content;
        # the `d:` default entry on clips handles anything written there later.
        "A+ /mnt/Shares/this-is-my-own-private-property-and-you-are-not-welcome-here - - - - u:jellyfin:x"
        "A+ /mnt/Shares/this-is-my-own-private-property-and-you-are-not-welcome-here/clips - - - - u:jellyfin:rX,d:u:jellyfin:rX"
      ];

      users.users.smbpublic = {
        isSystemUser = true;
        description = "Samba guest share user";
        group = "smbpublic";
        home = "/var/empty";
      };

      users.groups.smbpublic = { };

      services.samba = {
        enable = true;
        securityType = "user";
        openFirewall = true;
        settings = {
          global = {
            "workgroup" = "WORKGROUP";
            "server string" = "baaaalright";
            "netbios name" = "smbnix";
            "security" = "user";
            # 100.64.0.0/10 = the headscale tailnet — clients mount smb://100.64.0.3
            # directly over the mesh (the Mac's old sing-box 127.0.0.1:8445 forward
            # is retired). Without this, samba's `hosts deny 0.0.0.0/0` refuses the
            # tailnet even though port 445 is reachable.
            "hosts allow" =
              "100.64.0.0/10 192.168.3.0/24 192.168.2.0/24 192.168.1.0/24 10.89.0.0/24 127.0.0.1 localhost 10.8.0.1/24";
            "hosts deny" = "0.0.0.0/0";
            "guest account" = "smbpublic";
            "map to guest" = "bad user";
            "host msdfs" = "no";
          };
          "public" = {
            "path" = "/mnt/Shares/Public";
            "browseable" = "yes";
            "read only" = "no";
            "guest ok" = "yes";
            "create mask" = "0664";
            "directory mask" = "2775";
            "force user" = "smbpublic";
            "force group" = "smbpublic";
          };
          "semipublic" = {
            "path" = "/mnt/Shares/SemiPublic";
            "browseable" = "yes";
            "read only" = "yes";
            "guest ok" = "yes";
            "create mask" = "0664";
            "directory mask" = "2775";
            "write list" = "@phonkd phonkd";
            "force create mode" = "0660";
            "force directory mode" = "2770";
            "guest account" = "smbpublic";
          };
          "private" = {
            "path" = "/mnt/Shares/this-is-my-own-private-property-and-you-are-not-welcome-here";
            "browseable" = "yes";
            "read only" = "no";
            "guest ok" = "no";
            "create mask" = "0644";
            "directory mask" = "0755";
            "force user" = "phonkd";
            "force group" = "phonkd";
          };
        };
      };

      services.samba-wsdd = {
        enable = true;
        openFirewall = true;
      };

      networking.firewall.enable = true;
      networking.firewall.allowPing = true;
      services.avahi = {
        enable = true;
        nssmdns = true;
        publish = {
          enable = true;
          addresses = true;
          domain = true;
          hinfo = true;
          userServices = true;
          workstation = true;
        };
      };
      fileSystems."/mnt/Shares" = {
        device = "/dev/disk/by-id/virtio-shares";
        fsType = "ext4";
        autoFormat = true;
        autoResize = true;
        options = [
          "users"
          "nofail"
        ];
      };
      fileSystems."/mnt/solo-sata" = {
        device = "/dev/disk/by-id/virtio-solo-sata";
        fsType = "ext4";
        autoFormat = true;
        autoResize = true;
        options = [
          "users"
          "nofail"
        ];
      };
    };

  # ProtonVPN WireGuard full-tunnel egress for 203, run on the HOST (not the
  # UniFi gateway) so Tailscale can coexist. wg-quick's routing for a full
  # tunnel (AllowedIPs 0.0.0.0/0 with no explicit `table` -> wg-quick "auto")
  # uses fwmark + `ip rule ... suppress_prefixlength 0`, NOT a plain
  # `default dev wg0` in the main table. Tailscale independently installs its
  # own higher-priority ip-rules for its fwmark (0x80000, pref ~5210 << the
  # ~32764 wg-quick rules), so Tailscale's underlay bypasses wg0 and goes out
  # the real WAN (direct P2P), while everything else on 203 egresses via Proton.
  #
  # This replaces the UniFi policy-based route that used to force ALL of 203
  # through a gateway-level tunnel — which also captured Tailscale's STUN and
  # pinned 203 to DERP relay. That UniFi `203` PBR MUST be removed at cutover:
  # the fwmark split is local to 203, so if the gateway still policy-routes 203
  # by MAC it re-captures everything (incl. Tailscale) and defeats this.
  #
  # Only the client PrivateKey is secret (sops, server defaultSopsFile); the
  # server pubkey / endpoint / tunnel address are public config. The Proton
  # profile's `DNS = 10.2.0.1` is deliberately OMITTED: letting it rewrite
  # resolv.conf would fight Tailscale MagicDNS (100.100.100.100) + homelab-dns
  # and break 203's internal name resolution — external names still resolve via
  # homelab-dns (through 201), not leaked from 203. IPv6 is dropped for now (203
  # has no native v6; the Proton IPv4 endpoint is enough). No kill-switch yet: a
  # naive one would DROP Tailscale (its traffic leaves via the real WAN, not
  # wg0) — a Tailscale-aware kill-switch can be added later if wanted.
  flake.nixosModules."203-vpn" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "203-media") {
      sops.secrets.proton_wg_privatekey = { };

      networking.wg-quick.interfaces.wg0 = {
        address = [ "10.2.0.2/32" ];
        privateKeyFile = config.sops.secrets.proton_wg_privatekey.path;

        # Keep the observability push (loki/mimir at 10.9.0.1) OFF the tunnel.
        # wg-quick's `suppress_prefixlength 0` honors main-table routes more
        # specific than the default, so an explicit /24 via the LAN gateway
        # keeps 10.9.0.0/24 on the router path (which has the static route to
        # obs). Without it the full tunnel swallows the metrics push.
        # 192.168.1.1 = 203's default gateway (verified live: `ip route get`).
        postUp = ''
          ${pkgs.iproute2}/bin/ip route replace 10.9.0.0/24 via 192.168.1.1 dev ens18
        '';
        preDown = ''
          ${pkgs.iproute2}/bin/ip route del 10.9.0.0/24 via 192.168.1.1 dev ens18 || true
        '';

        peers = [
          {
            publicKey = "/i7jCNpcqVBUkY07gVlILN4nFdvZHmxvreAOgLGoZGg=";
            allowedIPs = [ "0.0.0.0/0" ];
            endpoint = "146.70.86.114:51820";
            persistentKeepalive = 25;
          }
        ];
      };
    };
}
