# Host-specific NixOS config for 203-spot (gigaplayer-server VM).
#
# flake.nixosConfigurations."203-spot" is generated by modules/builder.nix
# from lib/registry.nix. Cross-host modules (gigaplayer-server, server
# baseline) live in alwaysImport and self-gate on tags / is.server.
{ ... }:
{
  flake.nixosModules."203-spot" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "203-spot") {
      label.labels = [ "vm" ];
      networking.useDHCP = lib.mkDefault true;
      networking.interfaces.ens18.ipv4.addresses = [
        # {
        #   address = "192.168.3.203";
        #   prefixLength = 24;
        # }
        {
          address = "192.168.1.203";
          prefixLength = 24;
        }
      ];
      networking.firewall.allowedTCPPorts = [
        22
      ];
      swapDevices = [
        {
          device = "/var/lib/swapfile";
          size = 4 * 1024;
        }
      ];
      nix.gc = lib.mkForce {
        automatic = true;
        dates = "daily";
        options = "--delete-older-than 3d";
      };
      nix.settings.require-sigs = false;
    };
}
