# Host-specific NixOS config for 204-agent (hermes-agent server VM).
#
# flake.nixosConfigurations."204-agent" is generated by modules/builder.nix
# from lib/registry.nix. The server baseline (sops, global config) and the
# Proxmox/qemu base (oldblac-vm) are wired in via the registry entry; the
# hermes-agent NixOS module comes from inputs.hermes-agent.nixosModules.default.
#
# This file owns the bits unique to the 204-agent box: hostname, network
# interface, and the hermes-agent service configuration. The module self-gates
# on host.name so it's inert if accidentally imported elsewhere.
{ ... }:
{
  flake.nixosModules."204-agent" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "204-agent") {
      label.labels = [ "vm" ];
      networking.hostName = "204-agent";
      networking.interfaces.ens18.ipv4.addresses = [
        {
          address = "192.168.3.204";
          prefixLength = 24;
        }
      ];
      security.sudo.wheelNeedsPassword = false;
      networking.firewall.allowedTCPPorts = [
        22
        8095 # noobservability API
      ];
      environment.systemPackages = [
        pkgs.claude-code
      ];

      # llm-NOOBservability: natural-language questions -> LogQL/PromQL directly
      # against Loki/Mimir on the obs host, translated by qwen3.5:9b on 203's
      # ollama. API on :8095 (POST /api/ask, GET /api/health).
      services.noobservability = {
        enable = true;
        lokiUrl = "http://100.64.0.4:3100";
        mimirUrl = "http://100.64.0.4:9009/prometheus";
        ollamaUrl = "http://192.168.3.203:11434";
        model = "qwen3.5:9b";
        extraContext = ''
          Hosts (hostname label): 201-mono = reverse proxy (traefik, authelia,
          vaultwarden, paperless, DNS), 203-media = media server (jellyfin,
          *arr stack, sabnzbd, ollama), 204-agent = AI agents, observability =
          Loki/Mimir/Grafana host.
          Journal logs live in service_name="loki.source.journal"; select them
          by unit + hostname.
          Traefik access logs are service_name="traefik"; useful structured
          fields: RequestHost, RequestPath, RouterName, ClientHost,
          DownstreamStatus (sent to client), OriginStatus (what the backend
          returned) - the two diverging isolates a backend fault from a
          routing fault.
        '';
      };

      users.users.phonkd.extraGroups = [ "hermes" ];

      # ALIBABA_CODING_PLAN_API_KEY — the Alibaba Cloud Model Studio "Coding
      # Plan" subscription key, and the main model path since it replaced the
      # metered OpenRouter one. Hermes ships the provider profile built in as
      # `alibaba-coding-plan`: OpenAI-compatible endpoint
      # https://coding-intl.dashscope.aliyuncs.com/v1, key read from
      # ALIBABA_CODING_PLAN_API_KEY (or DASHSCOPE_API_KEY), base URL
      # overridable with ALIBABA_CODING_PLAN_BASE_URL. Mint the key in the
      # Model Studio console under the coding plan — a classic pay-as-you-go
      # DashScope key belongs to dashscope-intl.aliyuncs.com and 401s here.
      sops.secrets."hermes-alibaba" = {
        owner = "hermes";
      };
      # OPENROUTER_API_KEY — no longer the model path (see settings.model
      # below), kept only because the vision/image tools fall back to
      # OpenRouter when the main provider can't serve them. Safe to drop this
      # secret and its environmentFiles line once the coding plan has proven
      # itself.
      sops.secrets."hermes-openrouter-key" = {
        owner = "hermes";
      };
      # Discord config is split one env-var-per-secret (each decrypted file is a
      # single `KEY=VALUE` line). They were previously crammed into ONE secret
      # space-separated on a single line, so python-dotenv read the whole blob as
      # DISCORD_BOT_TOKEN's value → Discord rejected the malformed token with a
      # LoginFailure. One var per file keeps each value atomic and newline-clean.
      #   hermes-discord      → DISCORD_BOT_TOKEN=<bot token>
      #   hermes-discord-users→ DISCORD_ALLOWED_USERS=<comma-separated user IDs>
      #   hermes-discord-home → DISCORD_HOME_CHANNEL=<channel ID>
      sops.secrets."hermes-discord" = {
        owner = "hermes";
      };
      sops.secrets."hermes-discord-users" = {
        owner = "hermes";
      };
      sops.secrets."hermes-discord-home" = {
        owner = "hermes";
      };
      # GITHUB_TOKEN (fine-grained PAT) — for the gh CLI only. The Copilot API
      # rejects PATs of any kind ("Personal Access Tokens are not supported"),
      # regardless of the Copilot Requests permission.
      sops.secrets."hermes-github" = {
        owner = "hermes";
      };
      # COPILOT_GITHUB_TOKEN (gho_* OAuth token) — feeds the Copilot model
      # provider. Hermes resolves COPILOT_GITHUB_TOKEN > GH_TOKEN > GITHUB_TOKEN,
      # so this outranks the PAT above. Minted via the GitHub device-code flow
      # with the Copilot CLI client ID (Ov23li8tweQw6odWQebz); doesn't expire
      # unless revoked or unused for ~a year. To re-mint: POST
      # github.com/login/device/code with that client_id, approve, poll
      # login/oauth/access_token, then update this secret.
      sops.secrets."hermes-copilot" = {
        owner = "hermes";
      };
      # CLAUDE_CODE_OAUTH_TOKEN for the delegated Claude Code CLI (the bundled
      # autonomous-ai-agents/claude-code skill shells out to `claude`). Uses the
      # Claude Pro/Max subscription — generate once with `claude setup-token`
      # on a logged-in machine, no per-token API billing. REQUIRED before deploy:
      # sops-nix fails activation if this key is missing from secret.yaml.
      sops.secrets."hermes-claude" = {
        owner = "hermes";
      };

      services.hermes-agent = {
        enable = true;
        addToSystemPackages = true;
        extraDependencyGroups = [ "messaging" ];
        # gh: GitHub toolset. claude-code + tmux + jq: the bundled
        # autonomous-ai-agents/claude-code skill delegates to the `claude` CLI
        # (print mode + interactive PTY via tmux; jq parses its stream-json).
        # The skill auto-seeds into ~/.hermes/skills on startup; terminal +
        # skills toolsets are already in the hermes-discord preset.
        # curl: used by skills that hit HTTP APIs directly (e.g.
        # mimir-alerting) — NOT on the service PATH otherwise, only the
        # system profile has it.
        extraPackages = [
          pkgs.gh
          pkgs.claude-code
          pkgs.tmux
          pkgs.jq
          pkgs.curl
          pkgs.git
        ];
        # Main model: qwen3.7-plus on the Alibaba coding plan
        # (hermes-alibaba). Replaced deepseek-v4-flash on OpenRouter, which
        # billed per token; the coding plan is a flat subscription. The
        # general-purpose flagship rather than a coder model, because this
        # agent mostly answers on Discord and drives tools, and delegates
        # actual code to the `claude` CLI. Other models the same key serves:
        # qwen3.6-plus, qwen3-coder-plus / qwen3-coder-next, kimi-k2.5, glm-5,
        # MiniMax-M2.5 — swap `default` below, nothing else changes.
        # A Copilot/gpt-5.4 attempt is parked: the API path itself works — the
        # hermes-copilot OAuth token gets live gpt-5.4 completions from
        # api.githubcopilot.com — but Hermes' credential pool in
        # ~/.hermes/auth.json kept a stale priority-0 entry seeded from the
        # GITHUB_TOKEN PAT, which outranks the OAuth token and 400s. To retry:
        # delete the credential_pool.copilot entries from auth.json, set
        # provider copilot / model gpt-5.4 here again, restart hermes-agent.
        # Hermes takes `model` as a bare string or as a mapping; the mapping is
        # what pins the provider, so the model name stays unprefixed (the
        # `vendor/model` form is OpenRouter routing syntax and would 404 here).
        settings.model = {
          default = "qwen3.7-plus";
          provider = "alibaba-coding-plan";
        };
        settings.discord.require_mention = false;
        settings.approvals.mode = "auto";
        # Enable the native Spotify toolset for Discord (default-off). Hermes
        # ships spotify_playback/devices/queue/search/playlists/albums/library
        # tools built-in (no MCP, no extra dependency group). Replaces the
        # default discord preset list, so hermes-discord is re-listed alongside
        # spotify. Auth is a one-time `hermes auth spotify` PKCE flow run on the
        # host; it captures the Spotify app client ID and persists the refresh
        # token in the state dir (~/.hermes), after which Hermes auto-refreshes.
        settings.platform_toolsets.discord = [
          "hermes-discord"
          "spotify"
        ];
        # Give Hermes semantic search over the personal-data archive.
        # Registered tool name: mcp_slop_trove_search_personal_data.
        settings.mcp_servers.slop_trove = {
          url = "http://127.0.0.1:9120/mcp";
          tools.include = [ "search_personal_data" ];
        };
        environmentFiles = [
          config.sops.secrets."hermes-alibaba".path
          config.sops.secrets."hermes-openrouter-key".path
          config.sops.secrets."hermes-discord".path
          config.sops.secrets."hermes-discord-users".path
          config.sops.secrets."hermes-discord-home".path
          config.sops.secrets."hermes-github".path
          config.sops.secrets."hermes-copilot".path
          config.sops.secrets."hermes-claude".path
        ];
      };

      # Custom Hermes skill: teaches it to create/list/delete Mimir alert
      # rules via the ruler HTTP API (see modules/observability.nix for the
      # Mimir side — no auth, filesystem ruler_storage backend, "homelab"
      # namespace managed declaratively by mimir-rules-sync). Dropped straight
      # into $HERMES_HOME/skills/, the same directory bundled skills like
      # "watchers" install themselves into — no code changes to hermes-agent
      # itself, just a SKILL.md, per Hermes' own skill-authoring convention.
      system.activationScripts.hermesMimirAlertingSkill =
        let
          skillFile = pkgs.writeText "SKILL.md" ''
            ---
            name: mimir-alerting
            description: "Create, list, and delete Grafana Mimir alert rules via its ruler HTTP API."
            version: 1.0.0
            author: phonkd homelab
            license: Unlicense
            platforms: [linux, macos]
            metadata:
              hermes:
                tags: [monitoring, alerting, mimir, prometheus, homelab]
                category: devops
                requires_toolsets: [terminal]
                related_skills: []
            ---

            # Mimir Alerting

            Create and manage Prometheus-style alert rules in the homelab's Grafana
            Mimir instance via its ruler HTTP API. No authentication, no CLI
            dependency — plain `curl`.

            ## When to Use

            - User asks to "alert me when X" / "watch X and notify me" for something
              already exposed as a metric in Mimir (node_exporter host metrics, or
              anything else scraped into Mimir).
            - User wants to see, change, or remove an alert rule created this way.

            ## Before you start

            - Address: `http://100.64.0.4:9009` — only reachable over the home
              site-to-site VPN; this host already has that route (it ships metrics
              there via Alloy).
            - Tenant: single-tenant homelab (`multitenancy_enabled: false`), so no
              `X-Scope-OrgID` header is needed — every request is implicitly tenant
              `anonymous` regardless of what (if anything) you send.
            - **Always use the `hermes` namespace for anything you create.** The
              `homelab` namespace is managed declaratively by nix
              (`modules/observability.nix`, the `mimir-rules-sync` service) and gets
              reset from a fixed rule set on every rebuild of the observability
              server — never write to it, and never run a "sync"-style bulk
              operation across all namespaces (see Pitfalls).

            ## Quick Reference

            | Operation | Method + Path |
            |---|---|
            | List every namespace/group | `GET /prometheus/config/v1/rules` |
            | Get one namespace (all its groups) | `GET /prometheus/config/v1/rules/hermes` |
            | Get one group | `GET /prometheus/config/v1/rules/hermes/<group>` |
            | Create/replace one group | `POST /prometheus/config/v1/rules/hermes` (body = single group, not wrapped in `groups:`) |
            | Delete one group | `DELETE /prometheus/config/v1/rules/hermes/<group>` |
            | Delete the whole namespace | `DELETE /prometheus/config/v1/rules/hermes` |
            | Check if a rule is actually evaluating/firing | `GET /prometheus/api/v1/rules` |
            | Check Alertmanager received it | `GET /alertmanager/api/v2/alerts` |

            ## Procedure

            1. **Write the rule group as YAML.** The POST body is a *single group
               object* — `name`, optional `interval`, and `rules` — not the
               `groups: [...]` wrapper a mimirtool rule file would use:

               ```yaml
               name: disk-alerts
               rules:
                 - alert: SomeDiskFull
                   expr: node_filesystem_avail_bytes{...} < 1e9
                   for: 5m
                   labels:
                     severity: warning
                   annotations:
                     summary: "..."
                     description: "..."
               ```

            2. **POST it to the `hermes` namespace:**

               ```bash
               curl -sS -X POST http://100.64.0.4:9009/prometheus/config/v1/rules/hermes \
                 -H "Content-Type: application/yaml" \
                 --data-binary @rule-group.yaml
               ```

               `{"status":"success",...}` means it's live — Mimir's ruler picks it
               up within its evaluation interval (default 1m unless you set
               `interval:`), no restart needed.

            3. **Verify it's actually evaluating** (don't just trust the 200):

               ```bash
               curl -sS http://100.64.0.4:9009/prometheus/api/v1/rules | grep -A5 <alert-name>
               ```

               Look for `"health": "ok"` and, once the condition is true,
               `"state": "firing"`.

            4. **Confirm delivery** if you need to be sure a firing alert actually
               reached Alertmanager (and from there, Discord):

               ```bash
               curl -sS http://100.64.0.4:9009/alertmanager/api/v2/alerts
               ```

            ## Pitfalls

            - **Never run a "sync"-style bulk operation across the whole tenant**
              (this mainly applies if you ever reach for `mimirtool rules sync`
              instead of plain curl — there's no such bulk endpoint to hit by
              accident via curl). It's a mirror operation: it deletes every
              namespace not present in what you give it, tenant-wide, not just
              missing groups within one namespace. Verified live once: an unscoped
              sync wiped an unrelated namespace *and* the real declarative
              `homelab` rules in one shot. Stick to POST/DELETE on your own
              `hermes` namespace only.
            - **Don't touch the `homelab` namespace.** It's reset from nix on every
              rebuild — anything you put there is temporary at best, and editing it
              risks fighting the declarative sync.
            - **A POST replaces the entire group.** If a group already has 3 rules
              and you POST a version with 1, the other 2 are gone. `GET` the
              current group first if you're adding to it rather than replacing it.
            - Check `GET /prometheus/config/v1/rules/homelab` for the house style
              (thresholds, `for:` durations, `severity: warning` vs `critical`)
              before adding a new rule, so alerts feel consistent with the existing
              ones.

            ## Verification

            After creating or changing a rule, always:

            1. `GET /prometheus/api/v1/rules` and confirm the group/rule appears
               with `"health": "ok"`.
            2. If it's supposed to be firing right now, confirm `"state": "firing"`
               and that it shows up in `GET /alertmanager/api/v2/alerts`.
            3. Tell the user which namespace/group was created, and confirm it's
               `hermes`, not `homelab`.
          '';
        in
        {
          text = ''
            install -D -m 0644 \
              -o ${config.services.hermes-agent.user} -g ${config.services.hermes-agent.group} \
              ${skillFile} \
              ${config.services.hermes-agent.stateDir}/.hermes/skills/devops/mimir-alerting/SKILL.md
          '';
          deps = [ ];
        };

      # Personal-data embedding + semantic search (the "thing"); Hermes queries
      # it via the MCP entry above. Postgres + pgvector are created locally.
      services.slop-trove = {
        enable = true;
        database.createLocally = true;
        # 203-media's RTX 3060 Ti runs Ollama (passed through for Jellyfin
        # transcoding, see arr-slime.nix) — always on, unlike blac's 5080.
        # Same 192.168.3.0/24 as this host (203-media's ens19), no VLAN
        # crossing needed. blac also still runs ollama-cuda/bge-m3 if this
        # ever needs to move back (192.168.1.206:11434, cross-subnet).
        embedding.endpoint = "http://192.168.3.203:11434";
        embedding.model = "bge-m3";
        embedding.dim = 1024;
        mcp.port = 9120;
        sources.discord = {
          enable = true;
          path = "/var/lib/slop-trove/exports/discord";
        };
        sources.claude = {
          enable = true;
          path = "/var/lib/slop-trove/exports/claude";
        };
      };
    };
}
