# Host-specific NixOS config for 204-agent (hermes-agent server VM).
#
# flake.nixosConfigurations."204-agent" is generated by modules/builder.nix
# from lib/registry.nix. The server baseline (sops, global config) and the
# Proxmox/qemu base (oldblac-vm) are wired in via the registry entry; the
# hermes-agent NixOS module comes from inputs.hermes-agent.nixosModules.default.
#
# This file owns the bits unique to the 204-agent box: hostname, network
# interface, and the hermes-agent service configuration. The module self-gates
# on host.name so it's inert if accidentally imported elsewhere.
{ ... }:
{
  flake.nixosModules."204-agent" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "204-agent") {
      label.labels = [ "vm" ];
      networking.hostName = "204-agent";
      networking.interfaces.ens18.ipv4.addresses = [
        {
          address = "192.168.3.204";
          prefixLength = 24;
        }
      ];
      security.sudo.wheelNeedsPassword = false;
      networking.firewall.allowedTCPPorts = [
        22
      ];

      # Let the interactive user share HERMES_HOME with the gateway service.
      # The state dir (/var/lib/hermes) is 2770 hermes:hermes and
      # addToSystemPackages exports HERMES_HOME system-wide, so phonkd needs to
      # be in the `hermes` group to run `hermes portal login` (writes OAuth
      # creds into the shared HERMES_HOME). Alternatively: sudo -u hermes hermes ...
      users.users.phonkd.extraGroups = [ "hermes" ];

      services.hermes-agent = {
        enable = true;
        addToSystemPackages = true;
        settings.model = "anthropic/claude-sonnet-4-6";

        # No build-time secret. After the first rebuild, log in on the VM:
        #     hermes portal login      # OAuth into Nous, sets provider + model
        #     hermes portal info       # verify what's wired up
        #
        # Prefer API keys instead? Add a `hermes/env` entry (e.g.
        # ANTHROPIC_API_KEY=...) to modules/homelab/global-secrets/secret.yaml,
        # then uncomment:
        #     sops.secrets."hermes/env" = { };
        #     services.hermes-agent.environmentFiles =
        #       [ config.sops.secrets."hermes/env".path ];
        #     services.hermes-agent.settings.model = "anthropic/claude-sonnet-4";
      };
    };
}
