# Host-specific NixOS config for 204-agent (hermes-agent server VM).
#
# flake.nixosConfigurations."204-agent" is generated by modules/builder.nix
# from lib/registry.nix. The server baseline (sops, global config) and the
# Proxmox/qemu base (oldblac-vm) are wired in via the registry entry; the
# hermes-agent NixOS module comes from inputs.hermes-agent.nixosModules.default.
#
# This file owns the bits unique to the 204-agent box: hostname, network
# interface, and the hermes-agent service configuration. The module self-gates
# on host.name so it's inert if accidentally imported elsewhere.
{ ... }:
{
  flake.nixosModules."204-agent" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "204-agent") {
      label.labels = [ "vm" ];
      networking.hostName = "204-agent";
      networking.interfaces.ens18.ipv4.addresses = [
        {
          address = "192.168.3.204";
          prefixLength = 24;
        }
      ];
      security.sudo.wheelNeedsPassword = false;
      networking.firewall.allowedTCPPorts = [
        22
      ];

      users.users.phonkd.extraGroups = [ "hermes" ];

      sops.secrets."hermes-openrouter-key" = { owner = "hermes"; };
      sops.secrets."hermes-discord" = { owner = "hermes"; };
      sops.secrets."hermes-github" = { owner = "hermes"; };

      services.hermes-agent = {
        enable = true;
        addToSystemPackages = true;
        extraDependencyGroups = [ "messaging" ];
        extraPackages = [ pkgs.gh ];
        settings.model = "deepseek/deepseek-v4-flash";
        settings.discord.require_mention = false;
        settings.approvals.mode = "auto";
        # Give Hermes semantic search over the personal-data archive.
        # Registered tool name: mcp_slop_trove_search_personal_data.
        settings.mcp_servers.slop_trove = {
          url = "http://127.0.0.1:9120/mcp";
          tools.include = [ "search_personal_data" ];
        };
        environmentFiles = [
          config.sops.secrets."hermes-openrouter-key".path
          config.sops.secrets."hermes-discord".path
          config.sops.secrets."hermes-github".path
        ];
      };

      # Personal-data embedding + semantic search (the "thing"); Hermes queries
      # it via the MCP entry above. Postgres + pgvector are created locally.
      services.slop-trove = {
        enable = true;
        database.createLocally = true;
        # blac's RTX 5080 runs Ollama. TODO: set to blac's reserved static IP.
        embedding.endpoint = "http://192.168.3.206:11434";
        embedding.model = "bge-m3";
        embedding.dim = 1024;
        mcp.port = 9120;
        sources.discord = {
          enable = true;
          path = "/var/lib/slop-trove/exports/discord";
        };
      };
    };
}
