# Host-specific NixOS config for 205-builder (dedicated Nix remote build VM).
#
# flake.nixosConfigurations."205-builder" is generated by modules/builder.nix
# from lib/registry.nix. The server baseline (sops, global config) and the
# Proxmox/qemu base (oldblac-vm) are wired in via the registry entry.
#
# oldblac-vm imports builder-client, so this box inherits the client wiring
# too. A builder must not offload to itself, so below we import builder-server
# and mkForce the inherited client config off -- leaving 205-builder a pure
# build server. (Build-server config lives in builder-server; this file owns
# only the host-unique bits: hostname, IP, firewall.)
#
# Disk UUID caveat: this VM must be cloned from the existing oldblac VM
# template so partition UUIDs match what oldblac-vm.nix hardcodes (root
# f222513b-ded1-49fa-b591-20ce86a2fe7f, boot 12CE-A600). If you build a fresh
# disk instead, run `blkid` on the VM and override fileSystems."/".device and
# fileSystems."/boot".device here.
{ self, ... }:
{
  flake.nixosModules."205-builder" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    {
      imports = [ self.nixosModules.builder-server ];
      config = lib.mkIf (config.noughty.host.name == "205-builder") {
        label.labels = [ "vm" ];
        networking.hostName = "205-builder";
        networking.interfaces.ens18.ipv4.addresses = [
          {
            address = "192.168.3.205";
            prefixLength = 24;
          }
        ];
        security.sudo.wheelNeedsPassword = false;
        networking.networkmanager.dhcp = "internal";
        networking.firewall.allowedTCPPorts = [ 22 ];
        boot.loader.grub.configurationLimit = 10;

        # The Droid profile targets aarch64-linux. Register qemu-user for it
        # so Nix advertises the platform and can build its activation closure
        # on this x86_64 builder.
        boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

        # Server, not client: neutralize the builder-client wiring inherited
        # via oldblac-vm so this box never offloads builds to itself.
        nix.distributedBuilds = lib.mkForce false;
        nix.buildMachines = lib.mkForce [ ];
      };
    };
}
