# Host-specific NixOS config for 205-builder (dedicated Nix remote build VM),
# generated by modules/builder.nix from lib/registry.nix. Server baseline and
# the Proxmox/qemu base (oldblac-vm) come from the registry entry.
#
# oldblac-vm imports builder-client, so this box inherits the client wiring
# too -- a builder must not offload to itself, so below we import
# builder-server and mkForce the inherited client config off. This file owns
# only the host-unique bits: hostname, IP, firewall.
#
# Disk UUID caveat: this VM must be cloned from the existing oldblac VM
# template so partition UUIDs match what oldblac-vm.nix hardcodes (root
# f222513b-ded1-49fa-b591-20ce86a2fe7f, boot 12CE-A600). Building a fresh disk
# instead needs `blkid` on the VM and an override of fileSystems."/".device /
# fileSystems."/boot".device here.
{ self, ... }:
{
  flake.nixosModules."205-builder" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    {
      imports = [ self.nixosModules.builder-server ];
      config = lib.mkIf (config.noughty.host.name == "205-builder") {
        label.labels = [ "vm" ];
        networking.hostName = "205-builder";
        networking.interfaces.ens18.ipv4.addresses = [
          {
            address = "192.168.3.205";
            prefixLength = 24;
          }
        ];
        security.sudo.wheelNeedsPassword = false;
        networking.networkmanager.dhcp = "internal";
        networking.firewall.allowedTCPPorts = [ 22 ];

        # Droid profile targets aarch64-linux; register qemu-user so Nix can
        # build its activation closure on this x86_64 builder.
        boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

        # Server, not client: neutralize the inherited builder-client wiring
        # so this box never offloads builds to itself.
        nix.distributedBuilds = lib.mkForce false;
        nix.buildMachines = lib.mkForce [ ];
      };
    };
}
