# Host-specific NixOS config for 207-iot (Home Assistant VM).
#
# flake.nixosConfigurations."207-iot" is generated by modules/builder.nix
# from lib/registry.nix. The server baseline (sops, global config) and the
# Proxmox/qemu base (oldblac-vm) are wired in via the registry entry.
#
# Disk UUID caveat (same as 205-builder): oldblac-vm.nix hardcodes root/boot
# partition UUIDs, so this VM must be cloned from the existing oldblac VM
# template. If you build a fresh disk instead, run `blkid` on the VM and
# override fileSystems."/".device / fileSystems."/boot".device here.
#
# services.home-assistant.config is left unset (null) so HA's own onboarding
# wizard collects name/location/units/time zone on first browser visit --
# same as any fresh HA install. extraComponents just puts the Python deps
# for these integrations in the closure; add each one via Settings > Devices
# & Services > Add Integration once onboarding is done:
#   - apple_tv, yamaha_musiccast, jellyfin, spotify: config-flow (UI) setup.
#   - wake_on_lan: also config-flow, or a `switch:` YAML platform.
#   - yamaha (legacy YNC-over-HTTP): predates config-flow, YAML-only. If your
#     receiver doesn't do MusicCast, add a declarative `config.media_player`
#     stanza here once you have its host IP -- editing configuration.yaml by
#     hand won't survive a service restart unless config is managed here.
{ ... }:
{
  flake.nixosModules."207-iot" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "207-iot") {
      label.labels = [ "vm" ];
      networking.hostName = "207-iot";
      networking.interfaces.ens18.ipv4.addresses = [
        {
          address = "192.168.3.207";
          prefixLength = 24;
        }
      ];
      security.sudo.wheelNeedsPassword = false;
      networking.firewall.allowedTCPPorts = [
        22
        8123 # Home Assistant web UI
      ];

      services.home-assistant = {
        enable = true;
        extraComponents = [
          "default_config"
          "apple_tv"
          "yamaha"
          "yamaha_musiccast"
          "wake_on_lan"
          "jellyfin"
          "spotify"
        ];
      };
    };
}
