# Host-specific NixOS config for 207-iot (Home Assistant VM).
#
# flake.nixosConfigurations."207-iot" is generated by modules/builder.nix
# from lib/registry.nix. The server baseline (sops, global config) and the
# Proxmox/qemu base (oldblac-vm) are wired in via the registry entry.
#
# Disk UUID caveat (same as 205-builder): oldblac-vm.nix hardcodes root/boot
# partition UUIDs, so this VM must be cloned from the existing oldblac VM
# template. If you build a fresh disk instead, run `blkid` on the VM and
# override fileSystems."/".device / fileSystems."/boot".device here.
#
# Single-homed on 192.168.1.0/24 (the main LAN), not the 192.168.3.0/24
# management subnet the other 20X VMs use -- the Apple TV and Yamaha
# receivers live there, and mDNS/AirPlay discovery (apple_tv, yamaha_musiccast)
# doesn't cross subnets. oldblac-vm.nix hardcodes the gateway/nameservers for
# 192.168.3.0/24, so both are mkForce'd below to their 192.168.1.x
# equivalents (same trick 203-media uses for its own gateway override). One
# NIC only -- unlike 203-media this host doesn't dual-home onto .3.0/24, so
# it won't resolve *.int.phonkd.net/*.w.phonkd.net (served from
# 192.168.3.201); reach other homelab services by IP instead.
#
# services.home-assistant.config is left unset (null) so HA's own onboarding
# wizard collects name/location/units/time zone on first browser visit --
# same as any fresh HA install. extraComponents just puts the Python deps
# for these integrations in the closure; add each one via Settings > Devices
# & Services > Add Integration once onboarding is done:
#   - apple_tv, yamaha_musiccast, jellyfin, spotify: config-flow (UI) setup.
#   - wake_on_lan: also config-flow, or a `switch:` YAML platform.
#   - yamaha (legacy YNC-over-HTTP): predates config-flow, YAML-only. If your
#     receiver doesn't do MusicCast, add a declarative `config.media_player`
#     stanza here once you have its host IP -- editing configuration.yaml by
#     hand won't survive a service restart unless config is managed here.
{ ... }:
{
  flake.nixosModules."207-iot" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "207-iot") {
      label.labels = [ "vm" ];
      networking.hostName = "207-iot";
      networking.interfaces.ens18.ipv4.addresses = [
        {
          address = "192.168.1.207";
          prefixLength = 24;
        }
      ];
      # oldblac-vm.nix sets these for 192.168.3.0/24; override for this
      # subnet's router (which also does local DNS, mirroring how
      # 192.168.3.1 doubles as a nameserver for that VLAN).
      networking.defaultGateway = lib.mkForce "192.168.1.1";
      networking.nameservers = lib.mkForce [ "192.168.1.1" ];
      security.sudo.wheelNeedsPassword = false;
      networking.firewall.allowedTCPPorts = [
        22
        8123 # Home Assistant web UI
      ];
      # mDNS/Bonjour: apple_tv (pyatv) and yamaha_musiccast discovery -- both
      # autodiscovery and a manual-IP add go through zeroconf, which needs to
      # send/receive multicast on 5353. Without this, HA's firewall silently
      # drops the Apple TV's mDNS announcements and every scan comes back
      # empty, even when targeting its IP directly.
      networking.firewall.allowedUDPPorts = [ 5353 ];

      services.home-assistant = {
        enable = true;
        extraComponents = [
          "default_config"
          "apple_tv"
          "yamaha"
          "yamaha_musiccast"
          "wake_on_lan"
          "jellyfin"
          "spotify"
          # default_config's onboarding auto-creates config entries for these
          # (met: default weather; google_translate: default TTS;
          # radio_browser: default internet-radio) but nixpkgs only bundles a
          # component's extra PyPI deps if it's listed here explicitly --
          # otherwise they fail at startup with ModuleNotFoundError.
          "met"
          "google_translate"
          "radio_browser"
          # myStrom plug at 192.168.1.19 (see modules/shell.nix), auto-discovered
          # via DHCP/zeroconf now that HA is on the same LAN.
          "mystrom"
        ];
      };
    };
}
