# Host-specific NixOS config for g14 (ASUS Zephyrus laptop).
#
# flake.nixosConfigurations.g14 is generated by modules/builder.nix from
# lib/registry.nix. This module is referenced from the g14 entry's
# extraModules (because nixos-hardware imports can't safely live in
# alwaysImport -- imports must stay unconditional).
#
# Long-form pattern: `imports` is unconditional; `config` is gated as
# defense-in-depth even though only ever loaded on g14.
{ ... }:
{
  flake.nixosModules.g14 =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    {
      imports = [
        "${builtins.fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }}/asus/zephyrus/ga401"
      ];
      config = lib.mkIf (config.noughty.host.name == "g14") {
        # Shared desktop baseline (DE selection, steam, bluetooth, wheel,
        # networkmanager, nameservers, bolt, libinput quirks) now lives in
        # modules/desktop.nix, gated on noughty.host.is.nixosDesktop.
        #
        # The old sing-box proxy.ipRanges block is gone: g14 now reaches the
        # homelab over the headscale tailnet (modules/tailnet.nix), not a
        # local SOCKS proxy. The HM `proxy` module is Mac-only now.
        networking.hostName = "g14";

        boot.loader.systemd-boot.enable = false;
        boot.loader.limine = {
          enable = true;
        };
        boot.loader.efi.canTouchEfiVariables = true;

        systemd.tmpfiles.rules = [
          "w /sys/devices/system/cpu/cpufreq/boost - - - - 0"
        ];
        hardware.nvidia.prime = {
          offload.enable = lib.mkForce false;
          reverseSync.enable = true;
          allowExternalGpu = true;
        };
        programs.rog-control-center.enable = true;
        boot.extraModprobeConfig = ''
          options nvidia NVreg_EnableGpuFirmware=0
        '';
        hardware.nvidia = {
          open = false;
          powerManagement.enable = false;
        };
        systemd.services.nvidia-powerd = {
          unitConfig.StartLimitAction = "none";
          serviceConfig.Restart = "no";
          wantedBy = lib.mkForce [ ];
        };
        services.upower.enable = true;
      };
    };
}
