# Host-specific NixOS config for g14 (ASUS Zephyrus laptop).
#
# flake.nixosConfigurations.g14 is generated by modules/builder.nix from
# lib/registry.nix. This module is referenced from the g14 entry's
# extraModules (because nixos-hardware imports can't safely live in
# alwaysImport -- imports must stay unconditional).
#
# Long-form pattern: `imports` is unconditional; `config` is gated as
# defense-in-depth even though only ever loaded on g14.
{ ... }:
{
  flake.nixosModules.g14 =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    {
      imports = [
        "${builtins.fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }}/asus/zephyrus/ga401"
      ];
      config = lib.mkIf (config.noughty.host.name == "g14") {
        programs.steam.enable = true;
        hardware.bluetooth.enable = true;
        system.stateVersion = "26.05";
        users.users.phonkd.extraGroups = [ "dialout" ];
        networking.networkmanager.enable = true;
        home-manager.users.phonkd.proxy.ipRanges = [
          "192.168.1.47/32"
          "192.168.3.201/32"
          "192.168.1.46/32"
          "192.168.3.200/32"
          "192.168.1.150/32"
          "192.168.3.203"
          "10.9.0.0/24"
        ];
        networking.hostName = "g14";
        networking.nameservers = [
          "192.168.3.201"
          "1.1.1.1"
        ];

        boot.loader.systemd-boot.enable = false;
        boot.loader.limine = {
          enable = true;
        };
        boot.loader.efi.canTouchEfiVariables = true;
        services.hardware.bolt.enable = true;

        services.xserver.enable = true;

        services.greetd = {
          enable = true;
          settings = {
            default_session = {
              command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --remember --cmd start-hyprland";
              user = "greeter";
            };
          };
        };
        environment.etc."libinput/local-overrides.quirks".text = ''
          [Company Mouse Debounce Override]
          MatchName=*COMPANY*USB*Device*
          ModelBouncingKeys=1
        '';
        systemd.tmpfiles.rules = [
          "w /sys/devices/system/cpu/cpufreq/boost - - - - 0"
        ];
        hardware.nvidia.prime = {
          offload.enable = lib.mkForce false;
          reverseSync.enable = true;
          allowExternalGpu = true;
        };
        programs.rog-control-center.enable = true;
        boot.extraModprobeConfig = ''
          options nvidia NVreg_EnableGpuFirmware=0
        '';
        hardware.nvidia = {
          open = false;
          powerManagement.enable = false;
        };
        systemd.services.nvidia-powerd = {
          unitConfig.StartLimitAction = "none";
          serviceConfig.Restart = "no";
          wantedBy = lib.mkForce [ ];
        };
        services.upower.enable = true;
      };
    };
}
