# Host-specific darwin config for Eliss-MacBook-Pro.
#
# flake.darwinConfigurations.<name> is generated by modules/builder.nix
# from lib/registry.nix. HM wiring (gui homeModule) is handled by the
# generic darwinModules.gui-darwin in modules/hosts/types/gui/default.nix.
{ self, inputs, ... }:
{
  flake.darwinModules.macm4 =
    {
      pkgs,
      config,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "Eliss-MacBook-Pro") {
      # `deploy <host> [branch]` — deploy-rs wrapper (modules/deploy.nix).
      environment.systemPackages = [ self.packages.${pkgs.system}.deploy-cli ];

      # Mac-specific HM extras layered on top of what gui-darwin imports.
      home-manager.users.phonkd.imports = [
        self.homeModules.work
        inputs.sops-nix.homeManagerModules.sops
        {
          sops.age.keyFile = "/Users/phonkd/.config/sops/age/keys.txt";
          sops.defaultSopsFile = ../homelab/global-secrets/secret.yaml;
          sops.secrets.nixremote_key = {
            path = "/Users/phonkd/.ssh/nixremote_ed25519";
          };
        }
        {
          # Syncthing as a launchd user agent (nix-darwin has no syncthing
          # module; home-manager runs it under launchd on macOS). GUI on
          # http://127.0.0.1:8384 — pair with 201-mono there, same as the
          # servers do (they only `enable`, no declarative devices/folders).
          services.syncthing.enable = true;
        }
        {
          targets.darwin = {
            copyApps.enable = false;
            linkApps.enable = true;
          };
          # sing-box now carries ONLY the bedag work setup — see modules/proxy.nix.
          # Everything HOMELAB rides the headscale tailnet: hosts for ssh/deploy
          # (Tailscale SSH by identity), observability, SMB, AND homelab web
          # (`.w.phonkd.net` resolves to 201's tailnet IP 100.64.0.5 via the Mac's
          # scoped dnsmasq in modules/dns.nix, reaching traefik over the mesh).
          # Spotify-via-home was the last non-work rule and is gone too, which
          # retired the WireGuard outbound. Non-enrolled LAN boxes (Proxmox
          # 192.168.3.47) are reached by ssh-jump through 203 — below.
          # Finder SMB to 203 is now direct over the tailnet — no local forward:
          #   Finder > Cmd+K > smb://100.64.0.3
          # (203's samba `hosts allow` includes 100.64.0.0/10; see 203-media.nix.)
          # (day-to-day, observability is reached over the tailnet via the
          # `observability` alias below, and `deploy observability` targets
          # 100.64.0.4; see lib/registry.nix. Its non-tailnet break-glass
          # blocks are further down.)
          # ext-mail — same Hetzner :5432 + id_rsa. NB: 10.0.0.2 is the Hetzner
          # private range, and sing-box no longer has any tunnel outbound at all,
          # so this fixes the port/key but the connection only works from a
          # network that can already route there.
          programs.ssh.matchBlocks."10.0.0.2" = {
            port = 5432;
            identityFile = "~/.ssh/id_rsa";
            identitiesOnly = true;
          };
          # 205-builder distributed-build account, now over the tailnet (matches
          # nix.buildMachines.hostName = 100.64.0.2). nix.buildMachines passes the
          # key explicitly so offload works without this block; it's for manual
          # `ssh nixremote@100.64.0.2`. Scoped to `user nixremote` so the phonkd
          # login is untouched. (Tailscale SSH would authorise nixremote by
          # identity anyway; the key is the regular-sshd fallback.)
          programs.ssh.matchBlocks."205-builder-nixremote" = {
            match = "host 100.64.0.2 user nixremote";
            identityFile = "/Users/phonkd/.ssh/nixremote_ed25519";
            identitiesOnly = true;
          };

          # --- Tailnet (headscale mesh) -------------------------------------
          # Reach every enrolled homelab host by name over the tailnet, direct
          # (proxyCommand none defeats the bedag `Host *` SOCKS catch-all, which
          # otherwise routes even tailnet IPs through sing-box). These render
          # before that catch-all, so they win. Tailscale SSH authorises by
          # identity — no port/key/known_hosts to manage.
          programs.ssh.matchBlocks."201-mono" = {
            hostname = "100.64.0.5";
            user = "phonkd";
            proxyCommand = "none";
          };
          programs.ssh.matchBlocks."203-media" = {
            hostname = "100.64.0.3";
            user = "phonkd";
            proxyCommand = "none";
          };
          programs.ssh.matchBlocks."204-agent" = {
            hostname = "100.64.0.1";
            user = "phonkd";
            proxyCommand = "none";
          };
          programs.ssh.matchBlocks."205-builder" = {
            hostname = "100.64.0.2";
            user = "phonkd";
            proxyCommand = "none";
          };
          # obs is reached over the tailnet like every other host now:
          # `ssh observability`/`obs` and `deploy observability` (100.64.0.4).
          # The metrics/log data plane rides the tailnet too since
          # plans/retire-wg-obs.md — wg-obs is gone entirely.
          programs.ssh.matchBlocks."observability" = {
            host = "observability obs";
            hostname = "100.64.0.4";
            user = "phonkd";
            proxyCommand = "none";
          };

          # --- obs break-glass (tailnet is DOWN) ----------------------------
          # When the mesh is broken the `observability` alias above is useless,
          # so keep the two non-tailnet routes to obs's real sshd (:5432)
          # spelled out. Without a block here these addresses fall through to
          # the bedag `Host *` socat SOCKS catch-all (work repo, imported via
          # modules/work/external.nix) and die with a misleading
          # "peer might not be a socks4 server" / "Connection closed by UNKNOWN
          # port 65535" — hence proxyCommand none. The catch-all also forces
          # `IdentityFile ~/.ssh/id_ed25519` globally, which obs rejects; the
          # key it accepts is id_ed25519_priv, and first-match-wins in
          # ssh_config only works because these render above the catch-all.
          # The wg-obs route that used to be here is gone with the tunnel
          # (plans/retire-wg-obs.md). obs's public IP is now the only
          # break-glass path, which is no loss: it works from any network,
          # whereas the tunnel route only worked from home.
          programs.ssh.matchBlocks."obs-rescue-public" = {
            host = "obs-rescue-public 89.167.83.90";
            hostname = "89.167.83.90";
            port = 5432;
            user = "phonkd";
            identityFile = "~/.ssh/id_ed25519_priv";
            identitiesOnly = true;
            proxyCommand = "none";
          };

          # Raw tailnet IPs (deploy targets, MagicDNS FQDNs) go direct too.
          programs.ssh.matchBlocks."tailnet-cgnat" = {
            host = "100.64.0.*";
            proxyCommand = "none";
          };
          # Non-enrolled LAN boxes (Proxmox 192.168.3.47, etc.) are reached by
          # ssh-jump through 203 over the tailnet — no sing-box, no subnet
          # router. Verified: Mac -> 203(tailnet) -> Proxmox authenticates.
          programs.ssh.matchBlocks."homelab-lan-jump" = {
            host = "192.168.1.* 192.168.3.*";
            user = "phonkd";
            identityFile = "~/.ssh/id_ed25519_priv";
            identitiesOnly = true;
            proxyCommand = "ssh -o StrictHostKeyChecking=no phonkd@100.64.0.3 nc %h %p";
          };
        }
      ];

      system.stateVersion = 6;
      nix.settings.experimental-features = "nix-command flakes";

      # --- Offload x86_64-linux builds to the 205-builder VM -------------
      # The Mac can't build Linux natively, so point it at 205-builder for
      # x86_64-linux derivations (NixOS configs, ISOs, amd64 OCI images...).
      # The nixremote private key is delivered by sops-nix (homeManagerModules)
      # to /Users/phonkd/.ssh/nixremote_ed25519. The nix-daemon (root) reads it
      # there. Seed the builder's host key once after first deploy (over the
      # tailnet now — Tailscale SSH accepts it by identity):
      #   sudo -H ssh -i /Users/phonkd/.ssh/nixremote_ed25519 nixremote@100.64.0.2 true
      nix.distributedBuilds = true;
      nix.settings.builders-use-substitutes = true;
      nix.settings.trusted-users = [
        "root"
        "phonkd"
      ];
      nix.buildMachines = [
        {
          hostName = "100.64.0.2"; # 205-builder tailnet IP (was 192.168.3.205)
          sshUser = "nixremote";
          sshKey = "/Users/phonkd/.ssh/nixremote_ed25519";
          system = "x86_64-linux";
          maxJobs = 8;
          speedFactor = 2;
          supportedFeatures = [
            "nixos-test"
            "benchmark"
            "big-parallel"
            "kvm"
          ];
        }
        # aarch64-linux on the same box via qemu-user binfmt. See the matching
        # entry in modules/hosts/types/server/builder.nix for why it is a
        # second entry with reduced features rather than a wider `systems` list.
        {
          hostName = "100.64.0.2";
          sshUser = "nixremote";
          sshKey = "/Users/phonkd/.ssh/nixremote_ed25519";
          system = "aarch64-linux";
          maxJobs = 4;
          speedFactor = 1;
          supportedFeatures = [ "big-parallel" ];
        }
      ];
      security.pam.services.sudo_local = {
        enable = true;
        touchIdAuth = true;
      };
      system.defaults = {
        NSGlobalDomain = {
          NSWindowShouldDragOnGesture = true;
          NSAutomaticQuoteSubstitutionEnabled = false;
        };
      };
      system.primaryUser = "phonkd";

      users.users.phonkd.home = "/Users/phonkd";
      homebrew = {
        enable = true;
        enableZshIntegration = true;
      };
    };
}
