# Host-specific darwin config for Eliss-MacBook-Pro.
#
# flake.darwinConfigurations.<name> is generated by modules/builder.nix
# from lib/registry.nix. HM wiring (gui homeModule) is handled by the
# generic darwinModules.gui-darwin in modules/hosts/types/gui/default.nix.
{ self, inputs, ... }:
{
  flake.darwinModules.macm4 =
    {
      pkgs,
      config,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "Eliss-MacBook-Pro") {
      # `deploy <host> [branch]` — deploy-rs wrapper (modules/deploy.nix).
      environment.systemPackages = [ self.packages.${pkgs.system}.deploy-cli ];

      # Mac-specific HM extras layered on top of what gui-darwin imports.
      home-manager.users.phonkd.imports = [
        self.homeModules.work
        inputs.sops-nix.homeManagerModules.sops
        {
          sops.age.keyFile = "/Users/phonkd/.config/sops/age/keys.txt";
          sops.defaultSopsFile = ../homelab/global-secrets/secret.yaml;
          sops.secrets.nixremote_key = {
            path = "/Users/phonkd/.ssh/nixremote_ed25519";
          };
        }
        {
          # Syncthing as a launchd user agent (nix-darwin has no syncthing
          # module; home-manager runs it under launchd on macOS). GUI on
          # http://127.0.0.1:8384 — pair with 201-mono there, same as the
          # servers do (they only `enable`, no declarative devices/folders).
          services.syncthing.enable = true;
        }
        {
          targets.darwin = {
            copyApps.enable = false;
            linkApps.enable = true;
          };
          # Homelab hosts are reached over the headscale tailnet now (Phase 2 of
          # plans/headscale-mesh.md), NOT sing-box — so the 192.168.x ranges are
          # gone. sing-box keeps only its non-homelab roles: the obs wg range
          # (10.9.0.1 = Loki/Mimir + `deploy observability`, until Phase 3), plus
          # Spotify + `.w.phonkd.net` (the `domains` list in the sing-box wrapper)
          # and the bedag work VPN. Non-enrolled LAN boxes (Proxmox 192.168.3.47)
          # are reached by ssh-jump through 203 — see the ssh matchBlocks below.
          proxy.ipRanges = [
            "10.9.0.0/24" # observability over wg-obs (Phase 3 moves this too)
          ];
          # Finder SMB to 203 is now direct over the tailnet — no local forward:
          #   Finder > Cmd+K > smb://100.64.0.3
          # (203's samba `hosts allow` includes 100.64.0.0/10; see 203-media.nix.)
          # 10.9.0.1 = observability (Hetzner). Its sshd is on :5432 and
          # authorizes the id_rsa key; the generic proxy block only supplies the
          # SOCKS proxyCommand, so without this ssh -- and deploy-rs, which
          # honors ~/.ssh/config -- default to :22 + id_ed25519 and time out.
          # Rendered before `Host *`, so this port/key win.
          programs.ssh.matchBlocks."10.9.0.1" = {
            port = 5432;
            identityFile = "~/.ssh/id_rsa";
            identitiesOnly = true;
          };
          # ext-mail — same Hetzner :5432 + id_rsa. NB: 10.0.0.2 is the Hetzner
          # private range and is NOT in proxy.ipRanges above, so sing-box only
          # reaches it if the wg outbound already carries 10.0.0.0/8; if not,
          # this fixes the port/key but the connection still won't route.
          programs.ssh.matchBlocks."10.0.0.2" = {
            port = 5432;
            identityFile = "~/.ssh/id_rsa";
            identitiesOnly = true;
          };
          # 205-builder distributed-build account, now over the tailnet (matches
          # nix.buildMachines.hostName = 100.64.0.2). nix.buildMachines passes the
          # key explicitly so offload works without this block; it's for manual
          # `ssh nixremote@100.64.0.2`. Scoped to `user nixremote` so the phonkd
          # login is untouched. (Tailscale SSH would authorise nixremote by
          # identity anyway; the key is the regular-sshd fallback.)
          programs.ssh.matchBlocks."205-builder-nixremote" = {
            match = "host 100.64.0.2 user nixremote";
            identityFile = "/Users/phonkd/.ssh/nixremote_ed25519";
            identitiesOnly = true;
          };

          # --- Tailnet (headscale mesh) -------------------------------------
          # Reach every enrolled homelab host by name over the tailnet, direct
          # (proxyCommand none defeats the bedag `Host *` SOCKS catch-all, which
          # otherwise routes even tailnet IPs through sing-box). These render
          # before that catch-all, so they win. Tailscale SSH authorises by
          # identity — no port/key/known_hosts to manage.
          programs.ssh.matchBlocks."201-mono" = {
            hostname = "100.64.0.5";
            user = "phonkd";
            proxyCommand = "none";
          };
          programs.ssh.matchBlocks."203-media" = {
            hostname = "100.64.0.3";
            user = "phonkd";
            proxyCommand = "none";
          };
          programs.ssh.matchBlocks."204-agent" = {
            hostname = "100.64.0.1";
            user = "phonkd";
            proxyCommand = "none";
          };
          programs.ssh.matchBlocks."205-builder" = {
            hostname = "100.64.0.2";
            user = "phonkd";
            proxyCommand = "none";
          };
          # obs is dual-homed: `deploy observability` + Loki/Mimir still ride
          # wg-obs (the "10.9.0.1" block above, until Phase 3), but interactive
          # `ssh observability`/`obs` goes over the tailnet like every other host.
          programs.ssh.matchBlocks."observability" = {
            host = "observability obs";
            hostname = "100.64.0.4";
            user = "phonkd";
            proxyCommand = "none";
          };
          # Raw tailnet IPs (deploy targets, MagicDNS FQDNs) go direct too.
          programs.ssh.matchBlocks."tailnet-cgnat" = {
            host = "100.64.0.*";
            proxyCommand = "none";
          };
          # Non-enrolled LAN boxes (Proxmox 192.168.3.47, etc.) are reached by
          # ssh-jump through 203 over the tailnet — no sing-box, no subnet
          # router. Verified: Mac -> 203(tailnet) -> Proxmox authenticates.
          programs.ssh.matchBlocks."homelab-lan-jump" = {
            host = "192.168.1.* 192.168.3.*";
            user = "phonkd";
            identityFile = "~/.ssh/id_ed25519_priv";
            identitiesOnly = true;
            proxyCommand = "ssh -o StrictHostKeyChecking=no phonkd@100.64.0.3 nc %h %p";
          };
        }
      ];

      system.stateVersion = 6;
      nix.settings.experimental-features = "nix-command flakes";

      # --- Offload x86_64-linux builds to the 205-builder VM -------------
      # The Mac can't build Linux natively, so point it at 205-builder for
      # x86_64-linux derivations (NixOS configs, ISOs, amd64 OCI images...).
      # The nixremote private key is delivered by sops-nix (homeManagerModules)
      # to /Users/phonkd/.ssh/nixremote_ed25519. The nix-daemon (root) reads it
      # there. Seed the builder's host key once after first deploy (over the
      # tailnet now — Tailscale SSH accepts it by identity):
      #   sudo -H ssh -i /Users/phonkd/.ssh/nixremote_ed25519 nixremote@100.64.0.2 true
      nix.distributedBuilds = true;
      nix.settings.builders-use-substitutes = true;
      nix.settings.trusted-users = [
        "root"
        "phonkd"
      ];
      nix.buildMachines = [
        {
          hostName = "100.64.0.2"; # 205-builder tailnet IP (was 192.168.3.205)
          sshUser = "nixremote";
          sshKey = "/Users/phonkd/.ssh/nixremote_ed25519";
          system = "x86_64-linux";
          maxJobs = 8;
          speedFactor = 2;
          supportedFeatures = [
            "nixos-test"
            "benchmark"
            "big-parallel"
            "kvm"
          ];
        }
      ];
      security.pam.services.sudo_local = {
        enable = true;
        touchIdAuth = true;
      };
      system.defaults = {
        NSGlobalDomain = {
          NSWindowShouldDragOnGesture = true;
          NSAutomaticQuoteSubstitutionEnabled = false;
        };
      };
      system.primaryUser = "phonkd";

      users.users.phonkd.home = "/Users/phonkd";
      homebrew = {
        enable = true;
        enableZshIntegration = true;
      };
    };
}
