# Host-specific NixOS config for z14 (ASUS Zenbook 14 UM3406GA).
#
# flake.nixosConfigurations.z14 is generated by modules/builder.nix from
# lib/registry.nix; this module is referenced from the z14 entry's extraModules.
#
# Short, and deliberately so. This laptop briefly ran the `g14` config as a
# stopgap, but the two machines share almost no hardware: g14 is a Zephyrus
# GA401 with an NVIDIA dGPU, a Goodix fingerprint reader and ROG firmware, and
# this is a Zenbook with a Radeon 840M iGPU and neither of the other two. None
# of modules/hosts/g14/g14.nix's hardware blocks are carried over -- see
# plans/z14-zenbook.md for the side-by-side.
#
# What is *not* here is the interesting part. There is no nixos-hardware profile
# for the UM3406 upstream, and every generic thing its AMD-laptop profiles would
# set is already true in this config -- verified by eval rather than assumed:
# fstrim and enableRedistributableFirmware are on, hardware.graphics.enable32Bit
# comes with programs.steam, upower and power-profiles-daemon come with Plasma
# (which is also why tlp stays off), and the generated hardware-configuration.nix
# already carries hardware.cpu.amd.updateMicrocode. Importing the profiles would
# add a whole unpinned repo fetch to restate settings we already have.
{ ... }:
{
  flake.nixosModules.z14 =
    {
      config,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "z14") {
      networking.hostName = "z14";

      # Same bootloader as g14, and for a concrete reason beyond symmetry: the
      # stopgap rebuild onto the g14 config already installed limine to this
      # disk, so keeping it means this rename touches no boot path. No
      # secureBoot -- that is blac's, and it needs enrolled keys.
      boot.loader.systemd-boot.enable = false;
      boot.loader.limine.enable = true;
      boot.loader.efi.canTouchEfiVariables = true;

      # The one thing nixos-hardware's common/cpu/amd/pstate.nix would give us
      # on this kernel (it picks `active` for >= 6.3; we are on 6.18). Lets the
      # CPU do its own frequency scaling instead of acpi-cpufreq, which is the
      # more power-efficient path on recent Ryzen parts.
      boot.kernelParams = [ "amd_pstate=active" ];

      # This panel is OLED, so the one permanently-lit element on it -- the
      # taskbar -- gets hidden until the pointer asks for it. Exactly blac's
      # reasoning; see modules/kde.nix, which also drives the wallpaper
      # slideshow (the other half of the same burn-in story, and already on by
      # default for every KDE host, so it needs no line here).
      noughty.kde.panelAutoHide = true;

      # AirPlay audio *out*, carried over from g14 -- it is about the Sonos
      # speakers on this LAN, not about the GA401, so it belongs on whichever
      # laptop is in use. z14 is the sender: reachable AirPlay receivers become
      # ordinary PipeWire sinks, so anything (browser, mpv, Spotify) can pick
      # one as its output device. Receiving is the other stack entirely -- that
      # is shairport-sync on 203-media, see modules/gigaplayer.nix.
      #
      # Three parts, none of which PipeWire does on its own:
      #   1. avahi -- module-raop-discover browses mDNS through avahi's client
      #      library; with no daemon it finds nothing and no sink appears.
      #      Publishing stays off: the laptop only browses, it does not announce
      #      itself.
      #   2. module-raop-discover is not in PipeWire's default module set, hence
      #      the drop-in below.
      #   3. The firewall. RAOP hands the receiver a control and a timing port
      #      and the receiver connects *back* to them; the default-deny input
      #      chain drops that, and the failure is silent -- a Sonos answers the
      #      handshake up to SETUP and then simply never replies.
      #
      # Scope: AirPlay 1 (RAOP) receivers only. Anything insisting on HomeKit
      # pairing is out of reach -- PipeWire implements /auth-setup but not
      # pair-setup/pair-verify, which is why an Apple TV 403s the first OPTIONS.
      services.avahi = {
        enable = true;
        nssmdns4 = true;
        openFirewall = true; # UDP 5353 in, or the discovery replies are dropped
      };
      services.pipewire.raopOpenFirewall = true; # UDP 6001-6002: RAOP control + timing
      services.pipewire.extraConfig.pipewire."10-airplay" = {
        "context.modules" = [ { name = "libpipewire-module-raop-discover"; } ];
      };

      # Bluetooth audio: the best codec this laptop can actually reach.
      #
      # aptX Lossless is not it, and no amount of config makes it so. It is not
      # a codec in its own right but the top mode of aptX Adaptive R2, and the
      # only encoder that exists is Qualcomm's proprietary blob for Snapdragon
      # Sound hosts (Android/Windows). Nothing open implements it: libfreeaptx
      # -- the library PipeWire links for the aptX family -- stops at aptX and
      # aptX HD, and the pipewire in this closure builds exactly
      # {sbc, aac, aptx, aptx_hd, aptx_ll, ldac, lc3, opus, faststream, g722};
      # `ls $(dirname $(readlink -f $(which pipewire)))/../lib/spa-0.2/bluez5`
      # is the check. A headset advertising aptX Lossless negotiates down to
      # aptX HD, LDAC or AAC when it connects here.
      #
      # So the knob worth having is the ceiling of what *is* built, and that is
      # LDAC's bitrate. PipeWire defaults to "auto", which hands the choice to
      # Sony's ABR library: it opens below the top rate and backs off further
      # when the link is busy. "hq" pins 990 kbit/s, the highest-bandwidth path
      # this machine has to a headset. The trade is the usual one -- if it
      # stutters in a crowded 2.4 GHz room, "auto" goes back and that is the
      # whole fix.
      #
      # enable-sbc-xq is the same idea one tier down, for sinks that speak
      # neither LDAC nor aptX: SBC at ~452 kbit/s rather than ~328. Stated
      # rather than assumed, because the built-in spa default for it has moved
      # between releases.
      services.pipewire.wireplumber.extraConfig."10-bluez-quality" = {
        "monitor.bluez.properties" = {
          "bluez5.a2dp.ldac.quality" = "hq";
          "bluez5.enable-sbc-xq" = true;
        };
      };
    };
}
