# Host-specific NixOS config for z14 (ASUS Zenbook 14 UM3406GA).
#
# flake.nixosConfigurations.z14 is generated by modules/builder.nix from
# lib/registry.nix; this module is referenced from the z14 entry's extraModules.
#
# Short, and deliberately so. This laptop briefly ran the `g14` config as a
# stopgap, but the two machines share almost no hardware: g14 is a Zephyrus
# GA401 with an NVIDIA dGPU, a Goodix fingerprint reader and ROG firmware, and
# this is a Zenbook with a Radeon 840M iGPU and neither of the other two. None
# of modules/hosts/g14/g14.nix's hardware blocks are carried over -- see
# plans/z14-zenbook.md for the side-by-side.
#
# What is *not* here is the interesting part. There is no nixos-hardware profile
# for the UM3406 upstream, and every generic thing its AMD-laptop profiles would
# set is already true in this config -- verified by eval rather than assumed:
# fstrim and enableRedistributableFirmware are on, hardware.graphics.enable32Bit
# comes with programs.steam, and the generated hardware-configuration.nix already
# carries hardware.cpu.amd.updateMicrocode. Importing the profiles would add a
# whole unpinned repo fetch to restate settings we already have.
#
# upower and power-profiles-daemon are the one thing that stopgap g14/Plasma
# era got for free (Plasma's module enables both) and this host now has to ask
# for explicitly, having no desktop environment of its own -- see below. tlp
# stays off: it fights power-profiles-daemon over the same CPU governor.
{ inputs, ... }:
{
  flake.nixosModules.z14 =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    lib.mkIf (config.noughty.host.name == "z14") {
      networking.hostName = "z14";

      # Same bootloader as g14, and for a concrete reason beyond symmetry: the
      # stopgap rebuild onto the g14 config already installed limine to this
      # disk, so keeping it means this rename touches no boot path. No
      # secureBoot -- that is blac's, and it needs enrolled keys.
      boot.loader.systemd-boot.enable = false;
      boot.loader.limine.enable = true;
      boot.loader.efi.canTouchEfiVariables = true;

      # The one thing nixos-hardware's common/cpu/amd/pstate.nix would give us
      # on this kernel (it picks `active` for >= 6.3; we are on 6.18). Lets the
      # CPU do its own frequency scaling instead of acpi-cpufreq, which is the
      # more power-efficient path on recent Ryzen parts.
      boot.kernelParams = [ "amd_pstate=active" ];

      # No modules/kde.nix on this host to bring these in for free (see the
      # header comment) -- explicit, the way g14 also does for its own
      # reasons.
      services.upower.enable = true;
      services.power-profiles-daemon.enable = true;

      # This lid has a real ambient light sensor. It shows up as an IIO device
      # (`als`, HID usage 200041) behind the AMD sensor-fusion hub, with
      # illuminance, colour-temperature and chromaticity channels -- so the
      # hardware side of auto-brightness is not the problem on this machine.
      #
      # What was missing is a consumer. With nothing holding the device open,
      # in_illuminance_sampling_frequency sits at 0 and in_illuminance_raw
      # reads a flat 0 no matter how light the room is -- the HID sensor is
      # only polled once something asks it to be, which is exactly what this
      # daemon does. That reading-zero symptom is what sent us looking for a
      # broken sensor; the sensor was fine and simply asleep.
      #
      # iio-sensor-proxy is also the interface every desktop auto-brightness
      # implementation already speaks (GNOME's and KDE's both sit on
      # net.hadess.SensorProxy), so enabling it here is the prerequisite for
      # any of them rather than a commitment to one. Nothing on this host
      # changes the backlight by itself yet -- see plans/auto-brightness-z14.md
      # for what would, and why that last step is a taste call.
      hardware.sensor.iio.enable = true;

      # AirPlay audio *out*, carried over from g14 -- it is about the Sonos
      # speakers on this LAN, not about the GA401, so it belongs on whichever
      # laptop is in use. z14 is the sender: reachable AirPlay receivers become
      # ordinary PipeWire sinks, so anything (browser, mpv, Spotify) can pick
      # one as its output device. Receiving is the other stack entirely -- that
      # is shairport-sync on 203-media, see modules/gigaplayer.nix.
      #
      # Three parts, none of which PipeWire does on its own:
      #   1. avahi -- module-raop-discover browses mDNS through avahi's client
      #      library; with no daemon it finds nothing and no sink appears.
      #      Publishing stays off: the laptop only browses, it does not announce
      #      itself.
      #   2. module-raop-discover is not in PipeWire's default module set, hence
      #      the drop-in below.
      #   3. The firewall. RAOP hands the receiver a control and a timing port
      #      and the receiver connects *back* to them; the default-deny input
      #      chain drops that, and the failure is silent -- a Sonos answers the
      #      handshake up to SETUP and then simply never replies.
      #
      # Scope: AirPlay 1 (RAOP) receivers only. Anything insisting on HomeKit
      # pairing is out of reach -- PipeWire implements /auth-setup but not
      # pair-setup/pair-verify, which is why an Apple TV 403s the first OPTIONS.
      services.avahi = {
        enable = true;
        nssmdns4 = true;
        openFirewall = true; # UDP 5353 in, or the discovery replies are dropped
      };
      services.pipewire.raopOpenFirewall = true; # UDP 6001-6002: RAOP control + timing
      services.pipewire.extraConfig.pipewire."10-airplay" = {
        "context.modules" = [ { name = "libpipewire-module-raop-discover"; } ];
      };

      # Local LLM inference on the Radeon 840M. Three non-obvious choices here,
      # each of which cost a wrong turn to find.
      #
      # 1. Vulkan, not ROCm. rocminfo reports this iGPU as gfx1153, and
      #    nixpkgs' rocmPackages.clr.gpuTargets stops at gfx1151 -- so rocBLAS
      #    ships no code objects for this part, and ollama-rocm would need
      #    HSA_OVERRIDE_GFX_VERSION to masquerade as gfx1102 and hope the ISA
      #    is close enough. RADV needs none of that: it enumerates the device
      #    natively as "RADV GFX1153". The vulkan build is also a 34 MiB
      #    closure against ollama-rocm's 2.2 GiB of ROCm libraries.
      #
      # 2. OLLAMA_IGPU_ENABLE. Ollama finds the device and then deliberately
      #    discards it -- "dropping integrated GPU; to enable, set
      #    OLLAMA_IGPU_ENABLE=1" -- on the general theory that an iGPU is not
      #    worth the trouble. Without this the host silently falls back to CPU
      #    and the GPU never appears in `ollama ps`.
      #
      # 3. The unstable pin. nixos-26.05 carries ollama 0.32.3, and the
      #    registry refuses it: pulling qwen3.8 returns HTTP 412 "requires a
      #    newer version of Ollama". Qwen3.8 support landed in 0.32.13 and
      #    Flash-Next in 0.33.1; unstable is on 0.34.0. Drop this override once
      #    26.05 catches up -- nothing else here wants the newer version.
      #
      # Why a 27B fits at all: RADV exposes the 6 GiB BIOS UMA carve-out and
      # the ~12.5 GiB GTT aperture as a single 18.5 GiB heap, so a 16.5 GiB
      # q4_K_M 27B sits entirely in GPU-addressable memory with no partial
      # offload. GTT pages *are* ordinary system RAM though, so a loaded model
      # is charged against the same 25 GiB the desktop is using, and this host
      # has no swap -- keep an eye on num_ctx before blaming the GPU. Token
      # generation stays memory-bandwidth-bound either way (all ~16.5 GiB of
      # weights are read per token, over LPDDR5x shared with the CPU); the
      # iGPU earns its keep on prompt processing, not on tokens/s.
      #
      # user/group are set explicitly rather than left to the module's default
      # DynamicUser. A dynamic uid puts the model store under
      # /var/lib/private/ollama with ownership that is only stable for the
      # lifetime of the unit, which is a poor home for a 17 GiB blob store you
      # want to move in by hand or keep across a rebuild.
      services.ollama = {
        enable = true;
        package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system}.ollama-vulkan;
        environmentVariables.OLLAMA_IGPU_ENABLE = "1";
        user = "ollama";
        group = "ollama";
      };
    };
}
